### ISSUE TITLE
Add Turkish translation

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#117]
Add Turkish translation

**Comment by Alpdo** [comment]
I saw the original comment, if the commenter didn't respond I can help with the translation too.

**Comment by gdombiak** [comment]
Hey @feoranis26 , this is great new and perfect timing. I'm now working on the next major release and adding a few UI changes that require more translation. If you use Facebook could you send me a message? Most translators interact with me via Facebook messages. We can use email as a fallback.

Have you read [How do I add a new translation to OctoPod?](https://github.com/gdombiak/OctoPod/wiki/How-do-I-add-a-new-translation-to-OctoPod%3F)? You will need an XLIFF editor if you do not have one already.

Thanks,
Gaston

**Comment by jollino** [comment]
Gaston, I was thinking... while we figure out a way to centralize the translations, maybe we could create a Facebook group for it?

**Comment by gdombiak** [comment]
Love this idea Daniele. Could you help set it up? Did I say how much I like the idea? :) Thanks.Grazie.Gracias

**Comment by jollino** [comment]
There we go :) Once you join I'll add you as an admin! https://www.facebook.com/groups/octopod/

**Comment by feoranis26** [comment]
I'm sorry but i do not use facebook. If you have any other ways we can use
that but we can use email if that's alright with you.

Gaston Dombiak <notifications@github.com>, 12 Oca 2020 Paz, 20:07 tarihinde
şunu yazdı:

**Comment by feoranis26** [comment]
Maybe whatsapp?

Alp Doğaner <alpdoganer26@gmail.com>, 13 Oca 2020 Pzt, 15:52 tarihinde şunu
yazdı:

**Comment by feoranis26** [comment]
I'm sorry but i don't have facebook. Maybe whatsapp?

**Comment by gdombiak** [comment]
Send me an email to gdombiak at gmail and I will set you up.

Thanks again for your help.
Gaston

**Comment by gdombiak** [comment]
Closing ticket due to inactivity. Can reopen or create a new one once a translator is found.
