### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by dee-y** [gdombiak/OctoPod#122]
Hello, i am a graphic designer who loves contributing free logos to open source. I noticed you are without a logo, would you like me to contribute one to your project?

**Comment by gdombiak** [comment]
Hi dee-y,

Thanks for the offer. I would certainly be interested in adding a nice logo to OctoPod. How would you like to collaborate on this?

Thanks,
Gaston

**Comment by dee-y** [comment]
Owk great. Can you share more info on what Octopod is about. I understand it is a client for octoprint. What elements would you like to see in logo?

**Comment by gdombiak** [comment]
Got a new logo. Thanks for the offer.
