### ISSUE TITLE
Add support for doing PID calibration (bed & nozzle)

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#128]
Would be great to be able to enter the desired temp and run a bed or a nozzle PID calibration

Requestor: Chris Warkocki

**Comment by jollino** [comment]
Could this (and maybe other similar things) be configured on the plugin side? That way the app can just get a list of “operations” that could be configured and even shared, kind of like custom controls are. It may be a little redundant since custom controls could do just that though...

**Comment by gdombiak** [comment]
Closing ticket since there is now an easy way to execute this gcode commands from the terminal window via the popular gcode button
