### ISSUE TITLE
System Menu

### ISSUE THREAD

**Issue by Muerte1983** [gdombiak/OctoPod#141]
Would be very nice for me to get access to the system menu controls.  I have toggles for starting and stopping cam there. That's the only reason octoclient is still installed on my iPhone. 😉
Great work so far! 👏

**Comment by gdombiak** [comment]
Gracias Muerte! :)

I will work on this tonight and add it to the next release. This is a good one to have besides custom controls.

**Comment by Muerte1983** [comment]
Perfect! Thanks for your fast response. I hope it's not too much work to do this.

**Comment by gdombiak** [comment]
Half way there :)

![screen shot 2018-11-22 at 12 05 57 pm](https://user-images.githubusercontent.com/1791267/48920656-ff20ce80-ee4e-11e8-94b6-b28eda1ec14b.png)

**Comment by Muerte1983** [comment]
Great, thank you! 👏💪
