### ISSUE TITLE
Old Apple watch support???

### ISSUE THREAD

**Issue by Stady234** [gdombiak/OctoPod#143]
Is there any way to allow, even for a little bit, ability for the older watch os to be supported?

I have a gen 1, got this app, was that it had watch support.... when it wasnt on my watch i finally saw that it needs W OS 5... 

I am maxed at 4.3.2...

**Comment by gdombiak** [comment]
Hey Stady234, sorry to hear about this. I checked at OctoPod relies on several things that are only available on WatchOS 5.0. Will require some effort (no idea how much) to support 4.3. I will leave this ticket opened in case someone wants to contribute a backport to older versions.

**Comment by pranelio** [comment]
@gdombiak Hey, any chance that You have a list of WatchOS 5 features that OctoPod uses? I'd like to try to tackle this issue by either removing features or finding alternatives / workarounds.

**Comment by gdombiak** [comment]
Hi @pranelio, can't remember now which features require WOS 5. IIRC, if you try to deploy it in the simulator to a Watch OS 4.2 or older it should report which things won't compile. I will see if I can get any other info and post it back.

Thanks for your help. :)
Gaston

**Comment by Stady234** [comment]
Any progress?  I hope it isn't too much work, but it would be nice to have!

**Comment by gdombiak** [comment]
Hey Stady,

I'm currently not working on this. It is low on  my priority list so not sure if/when will get to this ticket. If someone wants to jump and help that would be awesome. Sorry for not giving the great news. :(

**Comment by Stady234** [comment]
Understandable.  I will keep watch of any further development.  I will close ticket, no need to have it lingering there!  Keep up the good work!
