### ISSUE TITLE
Camera rotation on Apple Watch. 

### ISSUE THREAD

**Issue by DavidSpek** [gdombiak/OctoPod#145]
Due to my camera mounting I have both vertical and horizontal rotation enabled in Octoprint. While the iOS app shows the video feed correctly, on my Apple Watch series 4 the video rotation has no changed so everything is upside down and mirror image.

**Comment by gdombiak** [comment]
Bug confirmed. I thought that I tested this but I guess I did not. Thanks for reporting it. Will fix it for next release.

**Comment by gdombiak** [comment]
Fixed! You will need to change camera orientation from OctoPrint or make any changes to printers in OctoPod so that Apple Watch gets proper camera configuration.
