### ISSUE TITLE
[German] Siri Command Responses do not replace variables

### ISSUE THREAD

**Issue by heiko7even** [gdombiak/OctoPod#155]
If i ask Siri for the remaining time or set the temperature it always responses with $(Time) or $(temperature) but not with real numbers 🙈

**Comment by gdombiak** [comment]
Could you post screenshots of the Siri shortcuts that have recorded phrases and also screenshots of what you get when you run them? That information will help troubleshoot the problem.

Thanks,
Gaston

**Comment by heiko7even** [comment]
Sure:

https://imgur.com/a/Om5cTYA

**Comment by gdombiak** [comment]
Vielen Dank. That helped figure out what is the reason for the error. Will push a new version tonight to the App Store. Apple usually processes submissions in less than 24 hours so tomorrow noon (PST) might have the new version out with the fix.
