### ISSUE TITLE
Use the keyboard's "return" to send gcode (+3 other small related things)

### ISSUE THREAD

**Issue by jollino** [gdombiak/OctoPod#162]
Very small issue, not urgent: I was fiddling with some manual gcodes and noticed that the "return" key on the keyboard does not trigger the action as the "send" button, as one would expect.

Bonus 1: once the text input is focused, hide the label and expand the input itself so there's more room to see the message itself (depending on the language and how long the label is, it may be more or less useful.)

Bonus 2, but not sure how convoluted this would be: when the keyboard is shown, the terminal output itself is half-hidden. Making it shorter so it fits the visible part would be nice, especially if typing multiple gcodes.

Bonus 3: (I swear this was just "ah I wish enter worked" but you know me :D) adding an input accessory view to allow recalling past commands, much like up and down arrow in octoprint itself. Doing this "per session" would be more than enough, so no need to save them on disk.

**Comment by gdombiak** [comment]
As always great ideas! Grazie
