### ISSUE TITLE
How to enable Apple Watch support

### ISSUE THREAD

**Issue by sblionel** [gdombiak/OctoPod#166]
I've installed OctoPod on my iPhone X and it's working great. I see that there is supposedly Apple Watch support, but OctoPod is not listed as an available app in Watch for my Apple Watch 2 (running WatchOS 5). What am I missing?

**Comment by sblionel** [comment]
That worked - thanks! Never had to do that before.

**Comment by gdombiak** [comment]
Sweet. Thanks for the update.
