### ISSUE TITLE
Add support for multi-languages

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#17]
OctoPod is being downloaded all around the world. We need to add the ability to translate the app to other languages.

Add Spanish support as a test.

**Comment by ArtCC** [comment]
Hi!

I was going to translate the application into Spanish but I see that you do not use the Localizable.string file, all the texts are blocked in the storyboard...

Regards. Arturo.

**Comment by gdombiak** [comment]
Hola Arturo,

You are correct. I'm now finishing last touches for the next 1.8 release and then start work on this issue. When I do this, I will need to add localization to soooo many places. Will let you know when ready to be translated.

Saludos
Gaston (de Argentina)

**Comment by ArtCC** [comment]
Ok. Do you speak spanish? Are you from Argentina?

Saludos.

**Comment by gdombiak** [comment]
Sip, de Buenos Aires. Me vine para usa hace unos 10 años. Vos de donde sos?

**Comment by gdombiak** [comment]
Hola Arturo, recién hice un push con cambios para agregar lenguajes. Para probar las cosas agregué Español (de Latino America). Fijate como anda para España y si queres agrega la versión correcta para España. Avisame si ves algun error en mi traducción.

Gracias.
Gaston

**Comment by gdombiak** [comment]
Genial. Gracias

**Comment by gdombiak** [comment]
Strings have been localized. Creating new issues for each new language
