### ISSUE TITLE
Camera shows blank/gray image

### ISSUE THREAD

**Issue by imro2** [gdombiak/OctoPod#171]
When I open OctoPod I see an error "Connection Failed - The data couldn't be read because it isn't in the correct format." with and option to Dismiss. When I dismiss it, OctoPod connects to the printer and everything but camera works. I am using raspberry pi with pi cam.

 I am able to open the camera stream url from phone browser. I am able to log into Octoprint from phone browser and watch the camera stream there. So I know it is configured correctly and there are not issues. 

It does not matter whether I am connected locally or accessing it over internet. I do have basic authentication enabled in HaProxy.

This is my webcam api response:
`

webcam |  
-- | --
bitrate | "5000k"
ffmpegPath | "/usr/bin/avconv"
ffmpegThreads | 1
flipH | false
flipV | false
rotate90 | false
snapshotSslValidation | true
snapshotTimeout | 5
snapshotUrl | "http://127.0.0.1:8080/?action=snapshot"
streamRatio | "4:3"
streamTimeout | 5
streamUrl | "/webcam/?action=stream"
watermark | true

`

**Comment by Cesar0415** [comment]
Did you ever find the solution? Having the same exact problem.

**Comment by gdombiak** [comment]
Hey guys,

Could you paste here the URL of the camera that you are using? It SHOULD NOT have _127.0.0.1_ as the hostname or the word _localhost_. Those 2 words mean something like _local computer_. The iPhone will try to connect to itself to get the camera and that won't work. 

Thanks,
Gaston

**Comment by gdombiak** [comment]
Closing ticket due to inactivity. We can reopen it or start a new one if this is still an issue
