### ISSUE TITLE
StarScream.wserror-Fehler 1 after updating to Octoprint 1.3.11

### ISSUE THREAD

**Issue by Coffey72** [gdombiak/OctoPod#175]
Got this error in Octopod after updating. And can’t see print time etc. I can connect and disconnect the printer   
who can help ? 
![2F84126F-B9E7-4247-8622-6DC27C062556](https://user-images.githubusercontent.com/46590686/57807103-c78d4200-7760-11e9-8434-8b751b2a1c9c.png)

**Comment by ferdaze** [comment]
I have had this issue for a couple months now.

**Comment by gdombiak** [comment]
Hey guys,

That error seems to indicate that websockets is failing to do the HTTP upgrade. Would you mind checking [OctoPrint's configuration guide](https://community.octoprint.org/t/reverse-proxy-configuration-examples/1107) in particular about using the _ proxy_http_version_ header? This is the most common reason for this problem.

Here is another thread in [OctoPrint's support](https://github.com/foosel/OctoPrint/issues/2941) that covers other reasons for this problem. 

Let me know how it goes.
Gaston

**Comment by Coffey72** [comment]
> Hey guys,
> That error seems to indicate that websockets is failing to do the HTTP upgrade. Would you mind checking OctoPrint's configuration guide in particular about using the _ proxy_http_version_ header? This is the most common reason for this problem.
> Here is another thread in OctoPrint's support that covers other reasons for this problem.
> Let me know how it goes.
> Gaston

Thanks for your Help, but i think the Picture confuses a little bit. 
The Cam is working. Anything is working on the OctoPrint Web Page. 

The Problem shows up only in the OctoPod App . Camara is running, i can Control the Printer etc. 
The Problem is that the estimated Time gets not displayed , the % gets not updated etc

**Comment by jollino** [comment]
Um, I may have found the culprit.

In OctoPrint's API Key Settings there's a checkbox for "Allow Cross Origin Resource Sharing (CORS) Needs restart"; I enabled that and restarted OctoPrint, and now I get the Terminal to stream properly on OctoPod. I don't have the time to prepare a print now but I think it may be the reason it wasn't working.

Note that in my specific case I'm using http (not https) against the local IPv4 address directly and I haven't changed anything about the network settings, other than setting a static IPv4 somewhere and disabling IPv6 so it's not reachable from the outside.

Oddly enough, however, the checkbox is unchecked after a reboot, yet it seems to work.

Not sure if it's just a huge coincidence, but maybe others can test this?

**Comment by Coffey72** [comment]
I checked it now. Looks like that this is the solution. Can’t check it in detail because the printer is off, but Octoprint is running.

**Comment by Coffey72** [comment]
> Um, I may have found the culprit.
> 
> In OctoPrint's API Key Settings there's a checkbox for "Allow Cross Origin Resource Sharing (CORS) Needs restart"; I enabled that and restarted OctoPrint, and now I get the Terminal to stream properly on OctoPod. I don't have the time to prepare a print now but I think it may be the reason it wasn't working.
> 
> Note that in my specific case I'm using http (not https) against the local IPv4 address directly and I haven't changed anything about the network settings, other than setting a static IPv4 somewhere and disabling IPv6 so it's not reachable from the outside.
> 
> Oddly enough, however, the checkbox is unchecked after a reboot, yet it seems to work.
> 
> Not sure if it's just a huge coincidence, but maybe others can test this?

This Solved it, could test it now. Thanks !

Mario
