### ISSUE TITLE
Not Refreshing when using OctoPrint 1.3.11

### ISSUE THREAD

**Issue by Neiljclements** [gdombiak/OctoPod#176]
Since OctoPrint upgraded to 1.3.11 I’m not getting any statistics regarding the print. All I get is video feed with nozzle and bed temps.

**Comment by jollino** [comment]
See #175

**Comment by Neiljclements** [comment]
My apologies. Should’ve searched the issues first. It happened straight after the upgrade, so I figured they’d messed with something.
Thanks for the super fast reply.

**Comment by gdombiak** [comment]
This is a valid error that was introduced when this ticket was resolved in OctoPrint. https://github.com/foosel/OctoPrint/issues/3024

You can use the workaround mentioned by @jollino until I release a new version with the proper fix. OctoPrint increased the security in the websockets area (see CORS) so now OctoPod is running into an issue. I solved it locally but need to test other things before the new release. Will see if I can push new version by the end of this weekend.
