### ISSUE TITLE
Accept hostname specified without http://

### ISSUE THREAD

**Issue by Patronics** [gdombiak/OctoPod#187]
A minor improvement, but could help resolve some onboarding confusion. I was about to post an issue to allow specifiying hostnames as IP addresses, which seemed to be nonfunctional, before trying putting http:// before the IP address. It would be helpful if the http could be automatically added if not specified, or at least a more helpful hint than "Please enter a valid URL" when specifying an IP address without http://

**Comment by gdombiak** [comment]
Love this idea. So simple and useful. Will see of adding it to the next release.
