### ISSUE TITLE
Add support for chamber temperature

### ISSUE THREAD

**Issue by B0rax** [gdombiak/OctoPod#197]
Octoprint recently added support for a chamber temperature. Meaning it will show up as a dditional temperature in the graph with a target that can be set via M141.
It would be great to have this in octopod as well.

**Comment by gdombiak** [comment]
Thanks for this idea. Will schedule it for the next release. I was not aware of this new feature. :)

**Comment by gdombiak** [comment]
Sneak peak:

![Screen Shot 2019-07-04 at 10 18 15 PM](https://user-images.githubusercontent.com/1791267/60699888-aae0d100-9eaa-11e9-96d3-9b2a448a1306.png)
![Screen Shot 2019-07-04 at 10 25 28 PM](https://user-images.githubusercontent.com/1791267/60699889-aae0d100-9eaa-11e9-88d3-a69db4d44f8f.png)

**Comment by jollino** [comment]
Any chance to make OctoPod also report the Pinda probe temperature? It shows as "P:xxx" in the temperature report

**Comment by B0rax** [comment]
Thank you very much!
