### ISSUE TITLE
Update icons to use newest design

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#199]
It is becoming a frequent request from users to update the icons used by the app. Need to find some other free library/site.

If you are reading this and know about icons that are newer and free to use please leave a comment. Thanks

**Comment by gdombiak** [comment]
https://remixicon.com/
https://material.io/tools/icons/

**Comment by pranelio** [comment]
https://icons8.com/
https://thenounproject.com/term/open-source/

**Comment by ZacharyKhan** [comment]
Any graphic designers willing to help make something?

**Comment by gdombiak** [comment]
New look with new icons....

![Screen Shot 2020-01-10 at 10 20 23 PM](https://user-images.githubusercontent.com/1791267/72199891-6739c780-33f7-11ea-9f19-0fd7d18893aa.png)

**Comment by jollino** [comment]
Would it be possible to add a button to only home X and Y, and Z separately?
There's a lot of space there and sometimes it can be handy to only do a partial home (e.g. when diagnosing issues; I recently had problems with the bearings and I often rehomed the Y axis only with a `G28 Y` before running an endless series of `G1 Yx Fy`

Default = `G28` [may need a W on Prusa to avoid triggering mesh bed leveling, can't check right now]
XY only = `G28 X Y`
Z only = `G28 Z`

**Comment by gdombiak** [comment]
Done. Implemented
![Screen Shot 2020-01-11 at 10 24 41 AM](https://user-images.githubusercontent.com/1791267/72208836-959dbe00-345c-11ea-9ab1-23a8b0daa68b.png)

Still thinking about dark icons over dark background ... not sure it's that easy to read

**Comment by jollino** [comment]
Great!
White-ish icons would definitely be more legible on a dark background, I think. Can that be changed programmatically depending on whether dark mode is enabled or not?

**Comment by jollino** [comment]
I was thinking that maybe the section title could be changed to "Axes" (or "Home axes") rather than "X Y Z" so it's more obvious what it refers to, and it's not like the "i" button that apparently many users didn't even think could contain other settings!

**Comment by gdombiak** [comment]
How about "Home"? Working now on adding Dark mode support. :)
