### ISSUE TITLE
Quick switch between printers

### ISSUE THREAD

**Issue by pranelio** [gdombiak/OctoPod#200]
I’ve marked the places where a swipe to left or right could witch between printers faster than clicking through a menu (at least in some cases). The old menu should stay, in case someone (a lucky someone) has dozens of printers. 

<img width="1366" alt="PNG image" src="https://user-images.githubusercontent.com/36538315/60761932-2930a500-a05c-11e9-90a6-450e1408f864.png">

**Comment by gdombiak** [comment]
I love this idea. I will explore how this can get done.

**Comment by gdombiak** [comment]
Implemented! Swipes on the navigation bar can be used for switching printers on the main panel.
