### ISSUE TITLE
Add slide to delete past gcodes in terminal

### ISSUE THREAD

**Issue by jollino** [gdombiak/OctoPod#208]
I use the gcode feature in terminal window a lot, but accidentaly mistyped a command a few days ago, and now it's very easy to trigger it again.
It would be nice to have a way to delete them one by one using the traditional slide to the left (like in Mail), or even just a way to nuke them all at once in the settings. Did I miss an obvious option, or is it not there yet? :)
Thanks!

**Comment by gdombiak** [comment]
Great idea. Will add a slide to remove from command history!
