### ISSUE TITLE
Webcam URL

### ISSUE THREAD

**Issue by dbird86** [gdombiak/OctoPod#211]
Is it possible to add a custom URL for the webcam. The app assumes the webcam address lives under the address for the octoprint instance. 

I run 3 seperate instances of Octoprint on one Raspberry Pi 3 so I have seperate addresses for each instance eg: http://<RPi-ipaddress>/printer1/, http://<RPi-ipaddress>/printer2/ and http://<RPi-ipaddress>/printer3/. The webcams live at http://<RPi-ipaddress>/webcam/, http://<RPi-ipaddress>/webcam2/ and http://<RPi-ipaddress>/webcam3/

Octopod automatically assumes the webcam address is: http://<RPi-ipaddress>/printer1/webcam/, http://<RPi-ipaddress>/printer2/webcam2/, etc so fails to display the webcam.

Is this possible to fix?

**Comment by gdombiak** [comment]
Hi,

Are you using the [Multicam plugin](https://plugins.octoprint.org/plugins/multicam/) as explained in the [FAQ page](https://github.com/gdombiak/OctoPod/wiki/FAQ-using-the-app#how-do-i-use-octopod-with-multiple-cameras)?

I have your same setup and works fine. Make sure that the multicam plugin is correctly configured and OctoPod will automatically pick up the configuration from OctoPrint.

**Comment by dbird86** [comment]
Oh yeah I got it to work, I just put in the full address in the standard webcam settings instead of just the relative path. Now it works in OctoPod :)

**Comment by gdombiak** [comment]
excellent. Closing ticket then
