### ISSUE TITLE
Change extrude by 100 to 50

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#213]
It is more convenient to control by units of 50 rather than a big 100.

**Comment by jollino** [comment]
I'm using the latest beta but I still have 100, and it does send a G1 E100. Maybe a localization issue?

![IMG_0340](https://user-images.githubusercontent.com/3470104/63094436-b377fd00-bf68-11e9-8195-b24ef6c2fc80.PNG)
![IMG_0341](https://user-images.githubusercontent.com/3470104/63094452-bffc5580-bf68-11e9-8e5f-56c558fefae2.PNG)

(Also, is there any way to see the current app version from within the app? I thought it was possible, but I can't find it)

**Comment by gdombiak** [comment]
Great detective work. You are right that the translation was still showing the old value. Fixed that and also added OctoPod version to the Settings page. New build is being processed.

Grazie!!!!

**Comment by jollino** [comment]
I was wondering... Maybe numbers should be "exempted" from being localizable strings, to prevent this sort of inconsistency in the future? After all a number is a number and iOS should possibly take care of formatting using the current locale (though that's likely not needed at all for an app like Octopod).

**Comment by gdombiak** [comment]
Yep, I think that if I remove the "translation" then xcode will show a warning and default to the one in english. The number that we see is actually a string/label so it shows as something that needs to be translated
