### ISSUE TITLE
Panel tab improvement - "rewind" to first page

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#216]
From Daniele Nicolucci:
'After scrolling to the other pages of the Panel tab, the only way to go back to the first one (the one with the temperatures) is to either scroll back or scroll beyond the last one. A nicer way would be to simply tap the Panel button in the tab bar itself to "rewind" to the first page, much like Instagram does if you scroll the stories view and tap the home button.'

**Comment by jollino** [comment]
Thanks!

**Comment by jollino** [comment]
Maybe the delegate issue could be worked around by keeping a reference to the current delegate before assigning to self, and then "forwarding" the event to it when we receive it? Sort of like calling the current method on `super` for extended classes. (Just throwing this here, haven't programmed for iOS in ages)
