### ISSUE TITLE
Add cell with date and time for expected print finish

### ISSUE THREAD

**Issue by simonbogh** [gdombiak/OctoPod#219]
Besides the two cells with `Print Time` and `Print Time Left`, for long prints or end-to-end printing, it would be nice to have an additional cell with e.g. `Print Finish: Aug. 28. 10.45 AM` simply by taking `Print Time Left`and adding it to current local time.

**Comment by gdombiak** [comment]
Was thinking that since many people use iPhone SE that has a small screen that instead of adding a new row for this information, how about doing a click on the "Print Time Left" row will flip and show "Print Finish:". It will work as a toggle between one and the other.

**Comment by gdombiak** [comment]
Implemented like this
![Screen Shot 2020-01-14 at 8 37 00 PM](https://user-images.githubusercontent.com/1791267/72405425-a6288f80-370d-11ea-8f33-ddd04b711d5b.png)
