### ISSUE TITLE
File name on 2 lines in the "Files" tab

### ISSUE THREAD

**Issue by slaading** [gdombiak/OctoPod#221]
My slicer generates automatic (long!) names with important informations regarding the settings so it could be useful to be able to distinguish 2 different files with slightly different settings.

The 2 lines solution is maybe not ideal for who has hundreds of files (not my case) but I can't think of a better idea.

**Comment by jollino** [comment]
Maybe the file name field could be made to scroll, like the infamous `<marquee>` tag of yesteryear's html?

**Comment by gdombiak** [comment]
Nice ideas guys! I will see what I can do about this. Tagging it for next release

**Comment by gdombiak** [comment]
Sébastien, I think you also mentioned this issue in the "job details" popup in the main page. When you click on the (i) next to Printed. Will see of improving that page too.

**Comment by slaading** [comment]
> Sébastien, I think you also mentioned this issue in the "job details" popup in the main page. When you click on the (i) next to Printed. Will see of improving that page too.
> 
> Same for file detail page.

Yes, great !

**Comment by slaading** [comment]
@jollino Scrolling is a great idea to save up some space but maybe really hard on the eyes when you have a full page of scrolling texts :)

@gdombiak I could satisfy myself by having the full name only in the file detail page. When in doubt about a file I would only click on it. Easy no?

**Comment by jollino** [comment]
> @jollino Scrolling is a great idea to save up some space but maybe really hard on the eyes when you have a full page of scrolling texts :)

Very true, I hadn't thought of that! Maybe the scrolling could be started and stopped on touch?

**Comment by gdombiak** [comment]
This is how it's looking so far ... 

Job details has up to 3 lines for file name: (_text translation is still in progress_)
![current job improved](https://user-images.githubusercontent.com/1791267/64067856-12ce4200-cbe4-11e9-8be2-0b3a5fd21ad2.png)

File details has unlimited number of lines for file name:
![file details improved](https://user-images.githubusercontent.com/1791267/64067857-12ce4200-cbe4-11e9-8573-8c130a3f4bef.png)

No changes here
![No changes here](https://user-images.githubusercontent.com/1791267/64067858-12ce4200-cbe4-11e9-8056-e1cd24b6986b.png)

**Comment by gdombiak** [comment]
I think that this solves this ticket. Let me know and I can commit the code and close the ticket!

Thanks guys,
Gaston

**Comment by slaading** [comment]
Looks great, thank you!
Maybe the « fichier » title could be vertically aligned to the top? ... sorry I’m a designer ;)

**Comment by gdombiak** [comment]
@slaading that is great feedback. Having a designer on board is awesome! I updated the screen as you suggested.
