### ISSUE TITLE
Palette 2 Plugin 2.3.1 ping/pong valuss

### ISSUE THREAD

**Issue by NelsonMB** [gdombiak/OctoPod#231]
After updating the Palette 2 plugin to 2.3.1, ping values are not appearing in OctoPod. Please see the attached screenshots. 
![4BA4A48A-EA3C-42F4-9AE9-FF7D841767AF](https://user-images.githubusercontent.com/19838657/69691712-d6549a00-109d-11ea-94a7-70eb993b752c.jpeg)
![F3899793-E146-4D7C-94ED-48DB93DD70AC](https://user-images.githubusercontent.com/19838657/69691713-d6549a00-109d-11ea-8a44-fd18bf764e1c.png)

**Comment by gdombiak** [comment]
Thanks @NelsonMB for reporting this issue. I just looked at the Palette 2 plugin and I see that its API got modified. I will update OctoPod app to be able to work with the old version of the plugin and the newest version of the plugin too. I guess that some people still run the older version so need to handle any version.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Hey @NelsonMB, I have a new beta version of OctoPod that addresses this issue. If you would like to help test the beta release to confirm it fixes this issue, you can send me an email to gdombiak at gmail dot com.

Thanks
