### ISSUE TITLE
Notification Settings

### ISSUE THREAD

**Issue by Neiljclements** [gdombiak/OctoPod#232]
It would be nice if we could choose which notifications we receive please.

Whilst a lot of them are useful, there are a few I don’t need to see like ‘Bed Below Temp Threshold’ 

Is this something that can be done?

**Comment by gdombiak** [comment]
Hi @Neiljclements,

Have you tried setting the value to 0 minutes in OctoPrint -> Settings -> OctoPod Notifications -> Bed Notifications? Except for "print done" notifications, all other notifications should be disabled when a value of 0 is set.

Let me know if this is not working as expected.
Thanks,
Gaston

**Comment by Neiljclements** [comment]
Watcha @gdombiak ! 
Thing is, I don’t want to kill notifications I’ve  or seen before that are really useful.
I got one today that OctoPrint hadn’t shown before that helped me diagnose an end script problem with the slicer.
I’ll have a play and see what happens.
Thanks for the reply.
I’ll close this now as I’m happy to crack on.
