### ISSUE TITLE
Keyboard accessory for number rows when 

### ISSUE THREAD

**Issue by jollino** [gdombiak/OctoPod#239]
One thing that would be nice, especially when debugging problems on the printer (e.g. rattling), is being able to type numbers more easily in the Gcode view. It would make series of similar commands much easier to handle.

I think an [input accessory view](https://developer.apple.com/documentation/uikit/uiresponder/1621119-inputaccessoryview) should be enough, just to show a row of numbers like Waze does:
![IMG_3695](https://user-images.githubusercontent.com/3470104/71999416-a58d8600-3241-11ea-8f7c-bdd734776613.PNG)

Bonus points for a readline-style arrow up and down to move through recent lines, but I think that may make the UI a bit more complicated.

(Note that is not directly related to the other UI/UX suggestions in #174 and #162.)

**Comment by gdombiak** [comment]
Hey Daniele,

Always amazed with your knowledge and great ideas. I think it is time for an OctoPod 3.0.0 with an improved UI/UX. Scheduled for next release (that will be a major release).

Grazie,
Gaston
