### ISSUE TITLE
Add info in full screen webcam view

### ISSUE THREAD

**Issue by nexux78** [gdombiak/OctoPod#251]
Is possible to add some information in full screen mode as layer height, bed and hotend temp, etc?

**Comment by gdombiak** [comment]
Great idea @nexux78. I can add bed and hotend temps. Marlin does not send OctoPrint any information about current Z or layer height. This means that OctoPod cannot have it either.

Perfect timing for this issue. I scheduled it for the next major release that should be out next week.

**Comment by gdombiak** [comment]
I will see if I can add also ETA

**Comment by nexux78** [comment]
Thank you!!!

**Comment by gdombiak** [comment]
![E97FCBF7-4F69-49FC-9F8B-2382145D3D71](https://user-images.githubusercontent.com/1791267/73229580-17653b00-412f-11ea-87ad-8ce3b014ae16.png)
![D4BE5F75-12AA-43E3-9F89-B3DB65930F06](https://user-images.githubusercontent.com/1791267/73229581-17653b00-412f-11ea-91a1-b1431c623bff.png)
