### ISSUE TITLE
Disconnect button should require confirmation

### ISSUE THREAD

**Issue by accountnumber3** [gdombiak/OctoPod#254]
I just cancelled a print because I wasn't connected to WiFi when I opened the app. I joined WiFi in the process but the app did not connect to octoprint immediately. 

I clicked connect.
The button changed to disconnect. 
I got a notification from my telegram bot that the print failed. 

Regardless of having connect and disconnect use the same space, the real issue is that the disconnect command is issued to octoprint, and not to the app. If that is the logic, then disconnect needs a confirmation prompt.

**Comment by jollino** [comment]
I'm not currently printing, but I gave it a try and I do get a confirmation prompt.
![IMG_4021](https://user-images.githubusercontent.com/3470104/73141562-c8af9680-4085-11ea-820d-d6f829bbffbc.PNG)

**Comment by gdombiak** [comment]
Hey @accountnumber3,

As Daniele said, OctoPod has a confirmation dialog on connect and disconnect. You can enable/disable this confirmation from the Settings tab.

![Screen Shot 2020-01-26 at 3 23 11 PM](https://user-images.githubusercontent.com/1791267/73143529-ea8e2680-404f-11ea-8bc8-eec427a993ac.png)

![Screen Shot 2020-01-26 at 3 23 15 PM](https://user-images.githubusercontent.com/1791267/73143531-f2e66180-404f-11ea-85c2-cbbc4f3a0e4a.png)

**Comment by accountnumber3** [comment]
Ok, I see it too. I think what happened is I was in a hurry and was tapping the connect button because I thought it meant connect for octopod to octoprint. I essentially created a race condition where I told octoprint to connect to the printer even though it was already connected. 
I guess I'd like a feature request to prevent commands from being sent if the state isn't verified.

**Comment by gdombiak** [comment]
Scheduled for the next release. Will check that the connect/disconnect button is active only after we really know the state.

**Comment by accountnumber3** [comment]
I see some really great updates. Not sure if this made it in but I'm not gonna test it. You can close this if you want

**Comment by gdombiak** [comment]
Still need to check that the connect/disconnect button is active only after we really know the state. Trying to implement for the coming release
