### ISSUE TITLE
Custom Controls not available during Print

### ISSUE THREAD

**Issue by Ruko2010** [gdombiak/OctoPod#255]
When I start a print, I cannot use my custom controls in octoprint to enable/disable my LED Strip. I installed the Strip to light up the printing area so I can see what is printing via webcam when its dark in the room. 
The strange thing is, that I can use the controls via the octoprint webinterface, even during print. The controls are working when no print is in progress. 
![9FA7BB63-1F4C-46C2-B14F-A7BAA5FD0CDC](https://user-images.githubusercontent.com/2239440/73291462-7ba3ff80-4200-11ea-9ec0-a669460adee4.png)

**Comment by gdombiak** [comment]
Hi @Ruko2010,

OctoPod has a safety feature that when enabled it will disable certain actions while printing to not interfere with the print job.  Custom Controls can potentially interfere with the print so they get disabled when this safety feature is enabled.

Go to Settings -> Security and disable "Auto-lock while printing". You can also manually disable "Lock read-only mode" and Custom Controls will become enabled again.

**Comment by gdombiak** [comment]
BTW, update to the recently released OctoPod 3.0 and enjoy the many new features. :) It went live today a few hours ago.

**Comment by Ruko2010** [comment]
Thanks for the really quick help. I‘ll test it on my next print. And yes, I‘ve already updated 😉. 
Btw, there are some german translations that won’t sound very good. Do you need help with that?

**Comment by gdombiak** [comment]
Sounds great.

Sure thing. You can see the translation in context which helps a lot. I try to provide as much context to translators as possible but things might get lost "in translation". :) Let me know which things I should update and I can update them for the next release.

Thanks,
Gaston

**Comment by Ruko2010** [comment]
I turned the safe option off and now the Custom control works while printing. Thanks for the help.

> Btw, there are some german translations that won’t sound very good. Do you need help with that?
I re-read the translations and realisied, they sound good. Maybe it was too late last time...^^
