### ISSUE TITLE
Terminal view improvements

### ISSUE THREAD

**Issue by jollino** [gdombiak/OctoPod#256]
When using the landscape view, landscape mode is great to see full lines, but it also means seeing fewer of them.

Compare:
![IMG_4003](https://user-images.githubusercontent.com/3470104/73303658-26bfb380-4217-11ea-9e01-3a5b51f1a830.PNG)

and:
![IMG_4003](https://user-images.githubusercontent.com/3470104/73303675-2d4e2b00-4217-11ea-87e3-af643406391f.PNG)

The keyboard makes things worse:
![IMG_4069](https://user-images.githubusercontent.com/3470104/73303765-4656dc00-4217-11ea-9a02-a273353c912f.PNG)

It would be nice if the app could "make room" to see more text, e.g. by hiding the tab bar below.
Even the update switch could be moved to the settings or removed entirely, in my humble opinion: I can't think of a single use case where you'd be in the terminal view without the terminal itself being updated...

**Comment by gdombiak** [comment]
Thanks Daniele for more great feedback. I do use the stop refreshing feature. :) What do you think if I switched the orders of those 2 fields. Comando GCode will appear first so that will give more room for the drop down. I will post a screenshot with that change before deciding adding logic to hide the numbers bar. Sounds good?

**Comment by jollino** [comment]
I admit I never tried disabling it, I'll have to see what it does. :D 
That would definitely help with the dropdown, in fact I was thinking about maybe having a separate button for the dropdown (maybe to the very right of the field, especially if the Send button is removed in favor of just pressing enter on the keyboard): tapping that button would show/hide the dropdown and, if needed, hide the keyboard.
It would also have the side effect of being able to type in the field freely without having the dropdown hide anything, even in portrait mode.
Not sure if that makes sense though, it's probably a lot of work for a very narrow use case.

On a side note, I noticed a few little things about the Italian translation that could be improved; I'll message you on FB with them. Did you happen to try any of those localization platforms, by the way?

**Comment by gdombiak** [comment]
Thanks so much Daniele. I haven't had time to check out those localizations tools. :( Will do as time allows.

Thanks,
Gaston
