### ISSUE TITLE
Reduce spacing on main Panel so it fits on one screen

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#259]
Example of 3.0
![Before](https://user-images.githubusercontent.com/1791267/73415523-051e0500-42c7-11ea-9135-fc8f06b0a158.png)

Example of what 3.1 could be
![After](https://user-images.githubusercontent.com/1791267/73415527-08b18c00-42c7-11ea-8b2e-af257b43200c.png)

**Comment by jollino** [comment]
Maybe the file name could be made part of the header line? "Print job: foo_bar.gcode"
And the ETA could be condensed into one line, e.g. "About 9min (6:42 PM)". Or maybe alternate between them on tap?
(Just brainstorming!)
