### ISSUE TITLE
Feature request: UX improvements

### ISSUE THREAD

**Issue by accountnumber3** [gdombiak/OctoPod#261]
After finishing a print I wanted to start another. My printer is not in the house so I figured I could use the webcam and controls nudge the print off the bed. It would have worked except that I'm stupid and impatient in all the worst ways. The part that I had printed is short but wide. I moved the Y axis as far out as it could go and X was somewhere in the middle. Being a complete moron I decided that the fastest way to get below the top of the print was to home Z. 
My maker select's cooling fan has a really solid steel mount which blended into the background and I forgot existed. I just turned that steel mount into a hydraulic press and smashed the shit out of my print. Except the print is nearly solid as well. The part that isn't so solid is the X carriage bars. I haven't gone out to check but it doesn't look good. In my panic the only things I could do was take a screenshot, and I didn't even do that.
Much too late I disconnected from the printer, reconnected, and sent Z shooting straight up. Octopod was set to XY increments of 10 while Z was 100. I probably clicked it a dozen times. 

Safety feature requests:
1. Disconnect button should be on every tab. It took a while to find it.
2. Tactile feedback on movement commands. I couldn't tell if I was actually hitting the buttons. Strength and/or duration should be variable based on the movement increment setting. Increments of 100 should be heavy and long. Increments of 0.1 should be light and short.
3. Add an `A` option to disable all motors, like a full stop.

**Comment by gdombiak** [comment]
Excellent excellent feedback! Implemented and now testing your great idea 2. Will add 3 later. Will see if I can do 1 for the next release. That will require more work.

**Comment by accountnumber3** [comment]
I don't know iOS programming but I imagine you could easily add a standard short vibration to all commands and make it fancy later.

For the disable all motors thing, I mean on the Move tab under Fan & Motors > disable motor, you already have `X Y Z E`. I'm suggesting to add `A` to that list to do all four. Just in case that wasn't clear.

Feel free to split these into multiple requests if you want

**Comment by accountnumber3** [comment]
Also, good news my printer is ok. Just had to re-level it. 😅

**Comment by gdombiak** [comment]
Haptic feedback tested and now committed. It's coming in the next release. Got to go now but will keep implementing your great ideas.

Happy to hear your printer survived! It was nice readying your story. Good writing style.

**Comment by jollino** [comment]
> For the disable all motors thing, I mean on the Move tab under Fan & Motors > disable motor, you already have `X Y Z E`. I'm suggesting to add `A` to that list to do all four. Just in case that wasn't clear.

Maybe, for consistency with the axis homing buttons, we could have a general "disable all" and then one additional button for each axis?

**Comment by gdombiak** [comment]
So add a new button to be able to "disable all" motors, correct? I think you both are suggesting this same thing.

**Comment by accountnumber3** [comment]
I'm not sure what he's asking for.

I'm looking for a little `A` or `All` right here:

![793FBF7B-F243-4C08-AC29-B514BE83995B](https://user-images.githubusercontent.com/33899447/73600406-a56d6700-451d-11ea-8a27-c10c1ddbd46f.jpeg)

**Comment by gdombiak** [comment]
Hey @accountnumber3, I think that is what Daniele is suggesting too. Due to localization needs, I'm leaning towards an icon rather than an A. IPhone SE/5/6 have narrow screens and some translations are large so no space for a whole word. :( 

How does any of these icon look for indicating multiple motors?
![Screen Shot 2020-02-01 at 4 07 03 PM](https://user-images.githubusercontent.com/1791267/73600946-24a66f00-450d-11ea-8af8-d516197ced04.png)

My vote is on the first icon.

Thanks
Gaston

**Comment by gdombiak** [comment]
Disable all motors button has been implemented for next release.

![Screen Shot 2020-02-01 at 6 16 39 PM](https://user-images.githubusercontent.com/1791267/73601931-ff226100-451e-11ea-90dd-a166a1ba5a6f.png)
