### ISSUE TITLE
Add Russian translation 

### ISSUE THREAD

**Issue by Caribsky** [gdombiak/OctoPod#266]

**Comment by gdombiak** [comment]
Hi @Caribsky , this is super exciting!!! Would you be able to help adding a Russian translation? :D

**Comment by Caribsky** [comment]
Hi @gdombiak 
Sure!

**Comment by gdombiak** [comment]
AWESOME! Do you have a facebook account? We have FB group for translators that we use for communication and when new translations are needed. I attached the XLIFF file that needs translation. You will need to use some XLIFF editor. If you use a free one make sure that it lets you save the translated text. Some people did a full translation to discover they needed to start all over again.

[ru.xliff.zip](https://github.com/gdombiak/OctoPod/files/4209278/ru.xliff.zip)

 Thanks and welcome to the family! :)

**Comment by Caribsky** [comment]
I wrote a message you on FB. 
Usually I use Xliff Editor (xliffedit.com)
Thanks

**Comment by gdombiak** [comment]
That's perfect. I use the exact same tool. It's great!

**Comment by Caribsky** [comment]
Hi @gdombiak! 
File with translation
[ru.xliff.zip](https://github.com/gdombiak/OctoPod/files/4217965/ru.xliff.zip)

**Comment by Caribsky** [comment]
Updated translation.
Overall improvements for iPhone 5/5s/SE
[ru.xliff.zip](https://github.com/gdombiak/OctoPod/files/4230307/ru.xliff.zip)

**Comment by gdombiak** [comment]
Thanks @Caribsky. I just incorporated your last version.
