### ISSUE TITLE
Read predefined heating temperatures from OctoPrint

### ISSUE THREAD

**Issue by ScharV** [gdombiak/OctoPod#272]
Could you please add the possibillity to change deferred temperatures of Bed and Nozzle? Would be nice for preheating with custom temperatures.

**Comment by gdombiak** [comment]
HI @ScharV, have you tried clicking on the pencil to set the temperature? See the image below for an example:
![Screen Shot 2020-03-19 at 4 37 34 PM](https://user-images.githubusercontent.com/1791267/77124420-0c78a980-6a00-11ea-8cd7-cbf544ca5bff.png)

Or are you looking for something different?
Thanks,
Gaston

**Comment by gdombiak** [comment]
You can enter any desired temperature on the "white entry field" at the top right

**Comment by ScharV** [comment]
Hi @gdombiak thank you for your fast reply.
Yeah i know this way. I mean it would be lovely to set the most used temperatures.
Hope you understand me🙈
I marked it on your picture.

![4E12959A-82E2-4438-A52D-8B15C3395BFD](https://user-images.githubusercontent.com/50781370/77148169-480e8480-6a8f-11ea-9f96-afa06a40e977.jpeg)

I would line to Change the 210 degrees in 200 degrees

**Comment by gdombiak** [comment]
Gotcha. This is a nice idea. I will make it so that OctoPod automatically reads temperatures set in OctoPrint's settings:

![Screen Shot 2020-03-20 at 9 24 29 PM](https://user-images.githubusercontent.com/1791267/77219265-4c6b8980-6af1-11ea-80f3-af3ab9189553.png)

Scheduling it for the next release

**Comment by ScharV** [comment]
@gdombiak Yeah thanks Sounds Great 💪🏼😬
