### ISSUE TITLE
Feature request - Add support for enclosure plugin - temperature probe

### ISSUE THREAD

**Issue by Sarithz** [gdombiak/OctoPod#277]
Love the app and what you have done.  One request I’d like to see is the ability to show temperature from a probe such as the DS18B20.  I tried looking at the settings but did not see anything obvious if it is already there.   Once again, wonderful work!

**Comment by gdombiak** [comment]
Thanks @Sarithz for the nice words! Nice sensor. I have the same for my other hobbies:
![simple test](https://user-images.githubusercontent.com/1791267/77381976-5f25ce80-6d3c-11ea-92f6-b053055d3700.jpg)

OctoPod takes all its information from OctoPrint. Is there an OctoPrint plugin that reads from that sensor? I can take a look and see if I can add support for that plugin (if one exists).

Thanks,
Gaston

**Comment by Sarithz** [comment]
Yes, sir.  Thanks for the quick response.  I use the Enclosure plugin for OctoPi https://github.com/vitormhenrique/OctoPrint-Enclosure from the plugin repository.

**Comment by gdombiak** [comment]
Gotcha. This seems to be a popular plugin so will add support for it in the next release. 3.2 is almost out the door now. I think I will start but showing sensors information. Not sure about other operations. Would that work for you?

**Comment by Sarithz** [comment]
Absolutely.  Thanks again if you need any help, let me know.  I’m not an android developer, but am an Apple one. 



Thank you,

James Barrett

**Comment by AnakinSpain** [comment]
Now I have 3.2 but I couldn't see the enclosure temperature. Is not implemented still?

**Comment by gdombiak** [comment]
Correct. This feature couldn't make it to the 3.2 release and is scheduled for the next 3.3 release. I'm now finishing the work for #286 and then planning to work on this feature.

**Comment by AnakinSpain** [comment]
Amazing work!!! Regards!

**Comment by gdombiak** [comment]
Progress so far
![Screen Shot 2020-04-12 at 9 35 20 AM](https://user-images.githubusercontent.com/1791267/79074395-f8dbfe00-7ca0-11ea-8304-44278a00d23a.png)

**Comment by AnakinSpain** [comment]
👍

**Comment by spatcho** [comment]
Hi, Great job and looking forward to test it - I m interested by the outputs, do you plan controlling them in that screen or in a new page like you do i.e. with the psu plugin ? I would prefer that later approach.

**Comment by gdombiak** [comment]
Hi @spatcho, for the next release I was planning to only expose temp data from this plugin. Now that you asked for output control ... I'm going to look into that and see if I can add it in this release as well. Yes, for output it will appear in its own subpanel as it works for the other plugins.

Thanks,
Gaston

**Comment by spatcho** [comment]
Thanks a lot, looking forward, and I will see to play with inputs too :-)

**Comment by gdombiak** [comment]
Added support for controlling GPIO and PWM outputs

![Screen Shot 2020-04-15 at 10 21 16 PM](https://user-images.githubusercontent.com/1791267/79417626-6f118680-7f67-11ea-9918-00f2847d3a52.png)

**Comment by spatcho** [comment]
I tested it on the simulator, I love it, thanks a lot ! I use it to turn on/off the printer and I would suggest a "are you sure to turn off" in a further release - usually I m not fan of this but it's easy to miss tap.

**Comment by gdombiak** [comment]
Good point @spatcho and thanks for testing out the new feature. Would you mind opening a new ticket for adding a confirmation dialog? I can add a new prompt setting to enable/disable those prompts and also apply your idea to the PSU Control plugin, TPLink/Tasmota/Wemos/etc and Enclosure plugins.

FYI, app was submitted to the store. It will become available to the public once Apple approved it.

Thanks,
Gaston

**Comment by spatcho** [comment]
Hi Gaston, thanks, yep i m gonna create the ticket
