### ISSUE TITLE
App needs fresh/modern Icon

### ISSUE THREAD

**Issue by Matthias1987** [gdombiak/OctoPod#278]
The App ist fantastic but the Icon with the blue frog is odd. The App really needs a fresh and modern Icon. I had this idea and made a new Icon.
What do you think?
![OctoPod App Icon](https://user-images.githubusercontent.com/55402373/77836000-8b818680-7152-11ea-80d5-7041da72edcf.jpg)

**Comment by gdombiak** [comment]
Hi @Matthias1987, your timing is perfect and thanks so much for helping with this. It is super needed. I'm at work now but will get back to you later today.

Thanks again,
Gaston

**Comment by Matthias1987** [comment]
Hi Gaston :)

Thanks for your Mail.
The App-Icon isn’t the final Version. I’ll work on it to look more like an octopus.
But I think this would fit with you App, which I use every day on iPhone, iPad an the Apple TV.

Best Regards
Matthias Petrat
(Editor | Author )

Blog: matthias-petrat.com <https://www.matthias-petrat.com/>
Podcast: Kolumnen-Podcast <https://itunes.apple.com/de/podcast/matthias-petrat-com-kolumnen-podcast/id1030896274?mt=2>
Twitter: @mp_com_blog <https://twitter.com/mp_com_blog>
Facebook: @matthiaspetrat@me.com.blog <https://www.facebook.com/matthiaspetrat.blog/>
Apple Bücher: Apple HomeKit - die Schnittstelle zum Zuhause <https://apple.co/2QOkUEf>

**Comment by Matthias1987** [comment]
Just had this idea 💡

**Comment by Neiljclements** [comment]
I like where it’s going, but it looks a bit flat and lacking colour / brightness

**Comment by Matthias1987** [comment]
Yes, but Icons are flat these days. Changed it a bit.
What do you think!

**Comment by Neiljclements** [comment]
I’m probably being dumb - highly likely - but I  can’t see the latest version. Is there a direct link?

**Comment by Matthias1987** [comment]
https://www.dropbox.com/s/o2cm5nwea58vxlf/Foto%2004.04.20%2C%2012%2014%2046.jpg?dl=0

Try this :)

**Comment by jollino** [comment]
Just my two cents here so take it with a grain of salt. :)

I like the shape of the octopus better, but I'm not sure how I feel about the circle and the flat color around it; my instinct is that it feels like overly convoluted (two background colors, with and blue, with a border in between) without adding much.

I've been staring at some of the app icons I have on my iPhone and I wonder how it would look if the octopus itself were placed directly against a slightly gradiented background (or vice versa: a gradiented octopus against a solid background; or even both), obviously with a much stronger contrast. For instance:

![image](https://user-images.githubusercontent.com/3470104/78425954-d3813b80-7673-11ea-95c3-1e3d84debcd0.png) ![image](https://user-images.githubusercontent.com/3470104/78426067-dd0aa380-7673-11ea-97b8-5461db96a564.png) ![image](https://user-images.githubusercontent.com/3470104/78426151-e267ee00-7673-11ea-89ac-f0cbeac4975f.png) ![image](https://user-images.githubusercontent.com/3470104/78426240-e85dcf00-7673-11ea-97db-546da699e6c9.png) ![image](https://user-images.githubusercontent.com/3470104/78426310-f01d7380-7673-11ea-8a4e-f045c7046555.png) ![image](https://user-images.githubusercontent.com/3470104/78430097-0d9f0d00-7675-11ea-8e16-103d01d42e68.png)

Or even just a strong contrast against the background, without any gradient:
![image](https://user-images.githubusercontent.com/3470104/78426854-193e0400-7674-11ea-8cab-daae900126c4.png) ![image](https://user-images.githubusercontent.com/3470104/78426957-20fda880-7674-11ea-9a1e-022180c7add0.png) ![image](https://user-images.githubusercontent.com/3470104/78427202-32df4b80-7674-11ea-8a3f-e218b2e83bd7.png) 
![image](https://user-images.githubusercontent.com/3470104/78427242-37a3ff80-7674-11ea-9acc-cd63195081b6.png) ![image](https://user-images.githubusercontent.com/3470104/78430581-30c9bc80-7675-11ea-8fc3-b6f807b2644b.png) ![image](https://user-images.githubusercontent.com/3470104/78431113-56ef5c80-7675-11ea-8c41-967873b319b9.png)

Maybe the background could be made a little quirky by adding a hint of gcode as a watermark, like Instapaper's icon: 
![image](https://user-images.githubusercontent.com/3470104/78429272-d29cd980-7674-11ea-9ecb-6738728bf237.png)

Again, just my two cents — Gaston knows that I like to throw all sorts of ideas around. :)

**Comment by Matthias1987** [comment]
Thanks for the idea!
So what about this?

**Comment by Neiljclements** [comment]
I’m liking where it’s going and I agree about a gradient on the border to give it a bit more pop, if you know what I mean?
And a small thing, could the mouth be a bit bigger? More smiley, if you know what I mean?

**Comment by gdombiak** [comment]
Looking better with each iteration. I like @Neiljclements's idea of a more smiley face to make it friendlier and explore the idea of gradient/solid backgrounds as @jollino suggested. @Matthias1987 I think that github is not rendering your last version, all we can see is the text of your reply.

Thanks everyone for making OctoPod a better app. So happy to see this community effort

**Comment by Neiljclements** [comment]
Yes, concur with @gaston I’m not seeing updated version you describe.

**Comment by jollino** [comment]
Same here, maybe replies via email filter out attachments?
@Matthias1987, can you try posting from Github's page? You should have a link to "view on github" at the bottom of the email. Just drag the file into the textbox and it'll upload and link it up for you.

**Comment by Matthias1987** [comment]
I think I got it 🤓
![CDDFBCCE-E0D9-48AA-9EEA-D6FF66E070FA](https://user-images.githubusercontent.com/55402373/78458704-a2286000-76b3-11ea-9914-69ae206515d4.jpeg)

**Comment by Neiljclements** [comment]
Ooh, yes, I like that. Much more cheerful! Would a thin border around the edge frame it a bit better? Slightly darker than the Octopus. 
Can always add it and take it away.
Really like where it’s going. Nice work dude. Making it look a simple is the hardest thing to do.

**Comment by Matthias1987** [comment]
Like this?
![0DC52976-FFE3-4F4A-AEEB-E0A7966B077C](https://user-images.githubusercontent.com/55402373/78459232-df8eec80-76b7-11ea-8b10-2d8b4630b697.jpeg)

**Comment by Neiljclements** [comment]
I meant a thin black border, just inside the edges of the icon. Although, the more I see that, the more and more I’m liking it. I think it lacks something and I can’t work our what it is. I feel like the octopus isn’t framed.
The other icons all have a gradient background, but that would probably mean reversing the colours and having the bg green and the octopus white, which I don’t think would work.
I’m not helping, am I?  Do you know what I’m clutching for? It just doesn’t pop like the other icons, and  I absolutely love the octopus graphic and think it deserves to jump out a bit.
Sorry, I’m hopeless....

**Comment by Neiljclements** [comment]
What about the octopus orange and the background a gradient dark to light blue? I think that would look awesome. Is it something you can easily try?

**Comment by Matthias1987** [comment]
This way?
![44DCDB98-AC3A-4F23-A85D-342A52E8413A](https://user-images.githubusercontent.com/55402373/78460186-013fa200-76bf-11ea-8c2c-a10d40843e3c.jpeg)

**Comment by Matthias1987** [comment]
Another try.
![13C50056-744D-4A53-B98D-D7F62AD9DC82](https://user-images.githubusercontent.com/55402373/78460569-28e43980-76c2-11ea-94b6-729747a01aa0.jpeg)
![42AB3995-1B87-4FCD-971A-F65BDB7C92FB](https://user-images.githubusercontent.com/55402373/78460573-300b4780-76c2-11ea-8d87-0ed5775e40a9.jpeg)

**Comment by Matthias1987** [comment]
The best one I think!
![F650B734-2514-4C15-8662-27AFAC53A6B1](https://user-images.githubusercontent.com/55402373/78461061-6d71d400-76c6-11ea-9e1f-b258e884a550.jpeg)
![AD88F2DE-5B6B-4178-A3D6-C6CF1ACAE1D4](https://user-images.githubusercontent.com/55402373/78461063-72368800-76c6-11ea-9a5f-fbd7a826481b.jpeg)

**Comment by Matthias1987** [comment]
Each time I compared them, I really like the turquoise one with the write background. It is just flat, simple, clean and understandable. Like the Colours on the white background from the Photos-App.

**Comment by Matthias1987** [comment]
I think that’s it. Clean, fresh, friendly.
![6EB9D4A3-FAB6-4901-8881-810127EAFB23](https://user-images.githubusercontent.com/55402373/78461469-77e19d00-76c9-11ea-969d-b88aa4b64941.jpeg)
![9F5C65C0-51BD-4E33-9D06-5BDE12A7A5DA](https://user-images.githubusercontent.com/55402373/78461472-7c0dba80-76c9-11ea-8a78-5b41a03e8392.jpeg)

**Comment by Matthias1987** [comment]
Last try. I made it much more friendly 😁
![DD098FC0-41CB-4B5D-8BBA-7678553A3B73](https://user-images.githubusercontent.com/55402373/78461629-16bac900-76cb-11ea-9767-0b4765b08931.jpeg)
![026E74F0-DAF7-4CE4-A1E4-39601BBC520B](https://user-images.githubusercontent.com/55402373/78461637-233f2180-76cb-11ea-9227-d202ed16d08f.jpeg)
![D65A7301-14DC-40E4-A650-6A4BD2F71C73](https://user-images.githubusercontent.com/55402373/78461638-23d7b800-76cb-11ea-8564-3d1a2f6ace31.png)

**Comment by Neiljclements** [comment]
Yeah, I’m leaning towards the turquoise more and more. I do like that orange on the dark, but it doesn’t hold me like the turquoise. Could you maybe make the background slightly darker to lift the octopus more?
I think you’ve nailed it though with the subtle changes to the octopus’ face. Has character now.
Really nice work dude. I wish I had that talent to bring life to an idea 👍🏽

**Comment by gdombiak** [comment]
Liking a lot this last version. The turquoise is very good since there is some of it in the images used in the buttons of the app.

**Comment by ScharV** [comment]
Just an idea 💡 what about 3 or 4 color variants to set in the settings of the app. So the user can choose his favourit design by himself. Like the Home+ App

![9B95E4A2-FDDC-4ABC-B9A7-BFA6980E7BAA](https://user-images.githubusercontent.com/50781370/78462197-17a22980-76d0-11ea-9429-41023d3bff3e.png)

**Comment by Neiljclements** [comment]
That’s a great idea. I’d forgotten about changing icon colour - perhaps use the orange on blue for one of them? 
Poor @Matthias1987 lol. Bet you wish you’d never started this escapade? Mind you, you’ve done an amazing job and really freshened up the logo.
Top work sir!

**Comment by Matthias1987** [comment]
Will create few styles over the day - stay tuned :)

**Comment by jollino** [comment]
I like the blue/turquoise background too, after all it's an octopus so it makes sense to have water around it!
Maybe a subtle gradient for the octopus itself (say from solid white to a very pale other color, maybe purplish? that's what I think most people associate octopi with) would give it a little extra punch? Something like this — I'm not a graphic designer so apologies in advance :D 
![image](https://user-images.githubusercontent.com/3470104/78472821-21617680-773c-11ea-8ee0-f5010e3e87e5.png)

**Comment by Neiljclements** [comment]
I think the background needs to be darker to pop the octopus out. It looks a bit faded.

**Comment by Matthias1987** [comment]
> I like the blue/turquoise background too, after all it's an octopus so it makes sense to have water around it!
> Maybe a subtle gradient for the octopus itself (say from solid white to a very pale other color, maybe purplish? that's what I think most people associate octopi with) would give it a little extra punch? Something like this — I'm not a graphic designer so apologies in advance :D
> ![image](https://user-images.githubusercontent.com/3470104/78472821-21617680-773c-11ea-8ee0-f5010e3e87e5.png)

![6D5FE035-E492-4373-B3CD-CCDEA9255E43](https://user-images.githubusercontent.com/55402373/78500465-da34af00-7756-11ea-99e7-45b4829ba7ce.png)

**Comment by Matthias1987** [comment]
Made it friendlier than ever. Gave it some shape (shadows in the background). Changed the colour.
![B84A4E66-2D38-4C87-92E2-4BD69D29CCA8](https://user-images.githubusercontent.com/55402373/78500694-511e7780-7758-11ea-8aad-9d85556b040b.jpeg)
![A00B680C-1E30-4173-8AB7-7DAD98113027](https://user-images.githubusercontent.com/55402373/78500703-57145880-7758-11ea-9d1d-05c3e5958777.png)
![F4ABFBCD-2CE1-4E81-A780-8B1FBBF09F23](https://user-images.githubusercontent.com/55402373/78500704-58de1c00-7758-11ea-9992-3e7311628cd7.jpeg)

**Comment by Matthias1987** [comment]
This are my last Ideas. Users can choose one of them.

![OctoPod App Icon 1](https://user-images.githubusercontent.com/55402373/78500858-3f899f80-7759-11ea-9ca8-bd804515367b.png)
![OctoPod App Icon 2](https://user-images.githubusercontent.com/55402373/78500860-40223600-7759-11ea-8939-8c2a22ec6623.png)
![OctoPod App Icon 3](https://user-images.githubusercontent.com/55402373/78500862-40bacc80-7759-11ea-97f8-1ea14f8659aa.png)
![OctoPod App Icon 4](https://user-images.githubusercontent.com/55402373/78500863-41536300-7759-11ea-8f14-f8569907aafd.png)

**Comment by Matthias1987** [comment]
Okay. Forget the post before.
This two styles are the very last ones. One light and one dark version of it.
![OctoPod App Icon 1](https://user-images.githubusercontent.com/55402373/78501038-4fee4a00-775a-11ea-992c-fe4126366ee2.png)
![OctoPod App Icon 2](https://user-images.githubusercontent.com/55402373/78501040-511f7700-775a-11ea-993d-5c0ae8b345a7.png)

**Comment by gdombiak** [comment]
My vote (and wife’s) goes to the latest from @jollino. Whiteish octopus with some minimal color and gradient gives a nice contrast

**Comment by Matthias1987** [comment]
![OctoPod App Icon 3](https://user-images.githubusercontent.com/55402373/78501681-f89da900-775c-11ea-8a09-19110d52036c.png)
So this one? 👍

**Comment by Neiljclements** [comment]
I like the one you’ve shown above as an icon and in the Apple TV. Perfect!
This one if the link works?

https://www.dropbox.com/s/3ap9es71ub7ce1e/IMG_0665.JPG?dl=0

**Comment by Neiljclements** [comment]
Yes, agree with @GDombiak - that’s the one! Let’s put an end to this madness 😂

**Comment by Matthias1987** [comment]
Okay. So which files do you need exactly to change the Icon for the Version of iOS, iPadOS and tvOS? 😄

**Comment by gdombiak** [comment]
All I need is an SVG and I think with that I can generate the tens of icons. I think no alpha or background transparency if I remember correctly

**Comment by gdombiak** [comment]
I think the one from @jollino is a little more whiteish? I’m on a phone so have to scroll and remember. Not ideal

**Comment by Matthias1987** [comment]
Changed it more to white on the top ans saved it as SVG. Give it a try 🤓
https://www.dropbox.com/s/l2nkkok9yoh0y6u/OctoPod%20Octopus%20App%20Icon%20Matthias%20Petrat.svg?dl=0

**Comment by Neiljclements** [comment]
All I can see is a black square with a pair of eyes 😂

**Comment by Matthias1987** [comment]
I think my design won't work as SVG. So I can make you the right Covers for each App as JPEG or PNG.

**Comment by gdombiak** [comment]
Ok. I can share Apple’s spec for each icon. It’ll have to be png

**Comment by gdombiak** [comment]
@Matthias1987 you are right, the SVG has some borders so I guess I cannot use it.

We need icons for [Apple TV that follow this spec](https://developer.apple.com/design/human-interface-guidelines/tvos/icons-and-images/app-icon/#app-icon-sizes) and for [iOS that follow this spec](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/).

For Apple TV we need to provide a background and foreground image and be careful with gradients. All this info is in the links I provided.

Thanks for all your help with this!
Gaston

**Comment by Matthias1987** [comment]
Here are all Icon. Just let me know if something is missing or incorrect.
Would be nice if you would link me in the protect because of the fresh Icon.
Just "Matthias Petrat (matthias-petrat.com)"

**Comment by gdombiak** [comment]
Wow. Super fast. Will update app later today and share results. Coding now the new dashboard to see all printers in the iOS app in a single page

**Comment by Matthias1987** [comment]
Nice. And when you do that, please make these Control-Icons a bit bigger and give them more space between each Icon, please 🤓
![IMG_4810](https://user-images.githubusercontent.com/55402373/78504420-6c47b200-776d-11ea-9645-2be459619adf.jpg)

**Comment by Neiljclements** [comment]
Amazing job @Matthias1987. You’ve really done a lovely job of that icon 😊👍🏽

**Comment by Matthias1987** [comment]
Thank you! 🙏🏻 
I’m glad you like it. Hope to push this project forward with my work. And I am no designer. Did all this work with Affinity Photo on my Mac. 😉
I just love good design.

**Comment by jollino** [comment]
Great stuff @Matthias1987!
![](https://media1.tenor.com/images/c386826214fd16f73421b1b4fbf634f7/tenor.gif?itemid=15328347)

On the topic of tweaking the buttons, @gdombiak, I was thinking that maybe the "home" buttons are not the easiest to read...
What if those buttons were the same height as the "move" buttons, and maybe had "X", "Y" and "Z" underneath or on the side? Perhaps the "home all" button could actually say "XYZ" to make it clearer — in hindsight, someone who's not familiar with these commands may get very confused by the home icon alone, especially as in most languages the word itself is different (e.g. in Italian it's "azzera", which has nothing to do with houses or homes.)
As always, just my two cents. :)

**Comment by gdombiak** [comment]
![image](https://user-images.githubusercontent.com/1791267/78732751-5ca8a480-78f8-11ea-82a7-8157da3f53d2.png)

Copied that icon from #291 suggested by @jessearmstrong

**Comment by Neiljclements** [comment]
Oh wow! That’s awesome! That looks super professional and I love the gold and black. Stunning!
