### ISSUE TITLE
Tasmota plugin not showing on v3.2b4

### ISSUE THREAD

**Issue by bdwilson** [gdombiak/OctoPod#279]
This previous enhancement (https://github.com/gdombiak/OctoPod/commit/7e7aa4faeba11bb922d88ad00ac6277b1f48e62d) worked fine until the recent upgrade. Only thing I see in the plugins section in Octopod app is "Custom Controls". This worked prior to 3.2 build 4. 

It’s the IPPlugViewController that isn’t showing. I now have a Custom Controls view where I used to have my Tasmota control. Tasmota plug-in version is 0.8.11, OctoPod plugin 0.2.5, OctoPrint 1.4 stable. This disappeared in a recent OctoPod update. I never had Custom Controls plugin installed yet that subpanel shows instead of IPPlugViewController.

**Comment by bdwilson** [comment]
It’s the IPPlugViewController that isn’t showing. I now have a Custom Controls view where I used to have my Tasmota control. Tasmota plug-in version is 0.8.11, OctoPod plugin 0.2.5, OctoPrint 1.4 stable. This disappeared recently - I believe it was when 1.4 went stable but worked on RC versions.

**Comment by gdombiak** [comment]
Hi @bdwilson, thanks for submitting this issue. There are no recent changes in OctoPod in this area so I wonder what is going on. Was this working fine before? I see that Tasmota 0.8.11 was recently released. Were things working fine with previous version of the plugin? I will install that version and try things locally.

**Comment by gdombiak** [comment]
Things appeared as expected. Here is how the plugin is configured
![Screen Shot 2020-03-30 at 8 53 03 PM](https://user-images.githubusercontent.com/1791267/77985255-ce656a80-72c8-11ea-8c1e-3da0318d7137.png)

and this is how it appears in the app:
![Screen Shot 2020-03-30 at 8 54 48 PM](https://user-images.githubusercontent.com/1791267/77985265-d8876900-72c8-11ea-8a02-cd05838e416f.png)

Could you share a screenshot of how your plugin is configured? Is the "Tasmota plugs" subpanel not appearing or it appears with no content?

The custom control subpanel always appears even if the custom control editor plugin is not installed.

**Comment by bdwilson** [comment]
Thank you for confirming it should still work. Here were my settings. 

https://bubba.d.pr/AuP3co

https://bubba.d.pr/lYFN4O

I removed the Plugin & data then reconfigured as per my old settings and it now shows up. I don’t believe me adding a name this time has anything to do with it.
