### ISSUE TITLE
Octopod not able to cancel/pause prints

### ISSUE THREAD

**Issue by Drakurius** [gdombiak/OctoPod#287]
Hello there,

For a while now I can start prints from octopod but the buttons to cancel/pause the prints are all greyed out. 

What can I do the re-enable the buttons?

Cheers from Germany

**Comment by gdombiak** [comment]
Hi @Drakurius , there is a security setting that will disable actions that may compromise the running print. In OctoPod, go to Settings -> Security and disable "Auto-lock while printing". If that check is disabled then make sure that "Lock read-only mode" is also disabled.
