### ISSUE TITLE
Layer Display broken with DisplayLayerProgress 1.19.1

### ISSUE THREAD

**Issue by ssnyder30** [gdombiak/OctoPod#296]
![IMG_1180](https://user-images.githubusercontent.com/31862891/79037212-ee384080-7b9c-11ea-8f68-1cf0b77e798c.jpeg)

**Comment by TheLion** [comment]
Same here.

**Comment by gdombiak** [comment]
Sorry guys about this. I'm in conversations with the developer of the DisplayLayerProgress plugin here https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/136. 

BTW, are you using OctoPrint-OctoPod plugin? Depending on what the developer of the plugin answers I might need to require the user of OctoPrint-OctoPod plugin to see layer information. A lot of users will basically lose seeing layer information if we go this way since not everyone uses OctoPrint-OctoPod plugin.

**Comment by TheLion** [comment]
> BTW, are you using OctoPrint-OctoPod plugin? 

Yes, I am.

**Comment by ssnyder30** [comment]
I am also using Octopod Plugin.

**Comment by sschwartzman** [comment]
For all interested, here's a simple workaround until this is fixed:

In settings for "State", set to `[current_layer] / [total_layers]` like so:
<img width="989" alt="Seth_s_Prusa_MK2_5S__OctoPrint_" src="https://user-images.githubusercontent.com/3536684/79141494-e8528300-7d87-11ea-8e1a-84a28607a8d3.png">

What you end up with in OctoPod:
![IMG_6093](https://user-images.githubusercontent.com/3536684/79141507-f1435480-7d87-11ea-8501-bbe80f656220.jpg)

...and in OctoPrint:
<img width="306" alt="Seth_s_Prusa_MK2_5S__OctoPrint_" src="https://user-images.githubusercontent.com/3536684/79141544-04eebb00-7d88-11ea-8597-cb6447048e3b.png">
(not ideal long-term, but totally fine by me for the time being)

@gdombiak Thank you for continuing to develop and support OctoPod! I use it religiously for my remote printing/monitoring needs. It's wonderful.

**Comment by gdombiak** [comment]
Thanks @sschwartzman. You are spot on, that is another workaround this issue. Thanks for sharing!!!

**Comment by JaySea77** [comment]
You asked if I wanted to beta test in the AppStore. Please tell me how.

**Comment by gdombiak** [comment]
Hey @JaySea77, good to see you here.  You will need to follow these steps:
1. Install plugin https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/download/1.20.0dev/master.zip. This will replace the version that you have with the new version that will be released. This version requires you to go to Settings and enable WebSocket-Communication. I asked the developer of the plugin to have that enabled by default for the final release
1. Install TestFlight app on your iPhone/iPad if you do not have it already installed. This is how Apple let's you install beta versions of applications
1. Open https://testflight.apple.com/join/Pq7JqNCx to accept installing Beta version of OctoPod
1. If you installed OctoPod in your Apple TV then you will need to also install TestFlight on your Apple TV and from there install the beta version of OctoPod

Let me know how it goes and if things are working fine or not.

Thanks,
Gaston

**Comment by JaySea77** [comment]
Thanks, the app now shows the layer again. Will try it with a print tomorrow.

**Comment by gdombiak** [comment]
Great to hear that @JaySea77. Thanks for helping test the new version and confirming that things are working. Let me know if you ran into something that needs fixing.

Gaston

**Comment by TheLion** [comment]
The dev version of DisplayLayerProgress and the OctoPod app from TestFlight, work great!

**Comment by gdombiak** [comment]
New version of the plugin is out. Ready to submit new version of OctoPod to the App Store.
