### ISSUE TITLE
Siri intent or quick action for printer shutdown

### ISSUE THREAD

**Issue by Floppy** [gdombiak/OctoPod#297]
My printer has my octoprint server inside it, powered by the same PSU, so whenever I want to turn off my printer, I need to shut down octoprint first. I always end up using Octopod to do that, so it would be really useful to be able to trigger that action via Siri, or by a 3d touch menu action.

**Comment by gdombiak** [comment]
Hi @Floppy, I follow your idea but need more information about exactly how you turn things off via OctoPod. Are you asking to be able to execute System Commands via Siri?

Thanks,
Gaston

**Comment by Floppy** [comment]
Using the "shutdown system" option in Octopod, under the System Commands menu, yes.

**Comment by gdombiak** [comment]
Gotcha. I will see what I can do with Siri command and System Commands. Commands are dynamic and need to check how Siri can handle that. Apple recently improved Siri to accept parameters so will see if that can help with this.
