### ISSUE TITLE
Starscream.WSError

### ISSUE THREAD

**Issue by SaJaToGu** [gdombiak/OctoPod#308]
I always get this error when opening the cam but I can the the cam without a problem. 
![66BA7B2C-7F98-4475-A3D1-DCC06891372B](https://user-images.githubusercontent.com/30648231/79902373-af628000-8411-11ea-97d7-46c7b173444b.png)

**Comment by gdombiak** [comment]
Hi @SaJaToGu, that error message is not related to the camera but to the websocket. Websocket connection is what the app uses for refreshing data like print time, progress, temps, terminal window, etc. When the app starts it also makes an HTTP request to fetch some data until websocket connection comes active. Having said all this, I'd say you see some data in the app but the data is not getting updated.

Are you using a reverse proxy to connect to OctoPrint?

**Comment by SaJaToGu** [comment]
Hi,I do not use a reverse proxy, but printing from the SD card. Is this maybe the problem?
Guido


Gesendet von Yahoo Mail für iPhone


Am Mittwoch, April 22, 2020, 05:54 schrieb Gaston Dombiak <notifications@github.com>:




Hi @SaJaToGu, that error message is not related to the camera but to the websocket. Websocket connection is what the app uses for refreshing data like print time, progress, temps, terminal window, etc. When the app starts it also makes an HTTP request to fetch some data until websocket connection comes active. Having said all this, I'd say you see some data in the app but the data is not getting updated.

Are you using a reverse proxy to connect to OctoPrint?

**Comment by gdombiak** [comment]
HI @SaJaToGu, printing from SD card or printing from OctoPrint is unrelated to connectivity problem. BTW, do you have upper case letters in the hostname? There was an issue reported recently about websockets failing to connect due to upper case letters in the URL.

**Comment by SaJaToGu** [comment]
Hi,Yes that was the problem.I changed to Ip adress and it is working without any errors now.
Thx
Guido 


Gesendet von Yahoo Mail für iPhone


Am Samstag, April 25, 2020, 00:53 schrieb Gaston Dombiak <notifications@github.com>:




HI @SaJaToGu, printing from SD card or printing from OctoPrint is unrelated to connectivity problem. BTW, do you have upper case letters in the hostname? There was an issue reported recently about websockets failing to connect due to upper case letters in the URL.

**Comment by gdombiak** [comment]
Great to hear that. This was reported here #298 and was fixed in the next version of OctoPrint. The root problem is in a library used by OctoPrint.
