### ISSUE TITLE
Add support for PrusaSlicer Thumbnails plugin

### ISSUE THREAD

**Issue by jon-daemon** [gdombiak/OctoPod#310]
We are able to have thumbnails in gcode files with PrusaSlicer and they are shown in Octoprint with [this](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails) plugin.
It will be great to see these thumbnails in file details view

**Comment by gdombiak** [comment]
This is such a great idea! Thanks @jon-daemon for filing this issue. Scheduled it for the next release.

**Comment by gdombiak** [comment]
![Screen Shot 2020-04-25 at 12 30 07 AM](https://user-images.githubusercontent.com/1791267/80273981-f2c82300-868b-11ea-845f-a9947e205c14.png)
![Screen Shot 2020-04-25 at 12 30 03 AM](https://user-images.githubusercontent.com/1791267/80273984-f52a7d00-868b-11ea-83de-0c7da09ca701.png)
