### ISSUE TITLE
[Feature Request] Show thumbnail

### ISSUE THREAD

**Issue by TheLion** [gdombiak/OctoPod#313]
Hi,

It would be really awesome, if OctoPod could show a thumbnail of the print when selecting a file in the "Files" section. 

Take a look at the [PrusaSlicer Thumbnails plugin](https://plugins.octoprint.org/plugins/prusaslicerthumbnails/), maybe you can utilize the functionality from that plugin.

**Comment by gdombiak** [comment]
It's already implemented for the next release. :) 

Tickets:
https://github.com/gdombiak/OctoPod/issues/310
https://github.com/gdombiak/OctoPod/issues/311

**Comment by TheLion** [comment]
> It's already implemented for the next release. :)
> 
> Tickets:
> #310
> #311

Hahaha. Didn't look at the closed issues, didn't think it would be implemented that quick 😜
