### ISSUE TITLE
Add setting to be able to hide camera for a printer

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#316]
Some people may not have a camera or may not be interested in seeing the camera as big. Allow users to slide the "bar" up to reduce camera screen size. Remember camera size so it can be used again when app starts. Slide down will be limited to what we can see now in the camera. Maybe allow to go bigger as long as image can still render fine.

**Comment by paviro** [comment]
I would also really like a possibility to hide the camera as I don't have one. Especially since the App is alerting me about connection errors because of it.

**Comment by wikolii** [comment]
I would love to see this implemented since not all my printers have cameras.
Maybe an option in the printers settings?
Thanks!

**Comment by gdombiak** [comment]
It is getting implemented! :)

![Screen Shot 2020-06-05 at 3 15 41 PM](https://user-images.githubusercontent.com/1791267/83926763-9dc60500-a73f-11ea-8159-04456a1a1a85.png)
![Screen Shot 2020-06-05 at 3 15 39 PM](https://user-images.githubusercontent.com/1791267/83926767-a0285f00-a73f-11ea-9d36-3612b5036efd.png)
![Screen Shot 2020-06-05 at 3 15 33 PM](https://user-images.githubusercontent.com/1791267/83926769-a1598c00-a73f-11ea-8a26-c3b9edcc767d.png)

**Comment by wikolii** [comment]
Hey, nice! Is this getting updated via the apple app store? Great job!

**Comment by gdombiak** [comment]
Hey @wikolii, the app has been submitted to the App Store for beta testing. My plan is to push it to the app store for an official release this week. I guess around Wednesday it will be live.
