### ISSUE TITLE
Enclosure plugin doesn’t change gpios

### ISSUE THREAD

**Issue by ciapamusche** [gdombiak/OctoPod#324]
Hi

When I try to toggle my relays in enclosure plugin in octopod I have error in request.

Other plugins works correctly 

Have some advice?

**Comment by gdombiak** [comment]
Hi @ciapamusche, I wonder whether you are running the latest version of the plugin. It should be 4.13.1. This was reported here #320. I will open a ticket with the enclosure developer to address this.

Let me know if that was your case.
Gaston

**Comment by ciapamusche** [comment]
Thank you for reply. There is actually a problem with Enclosure plugins. The update you indicated exist and solve the problem but octoprint not recognize automatically the version 4.13.1 So the walkaround is from octoprint page:

Go to settings
Plugin Manager
click Get more.
In the box "From url" paste the master release link
https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/master.zip


This solve the problem.

I hope is useful

**Comment by gdombiak** [comment]
Thanks for documenting how to manually solve this until https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/318 is addressed. Closing this ticket for now.

Thanks,
Gaston
