### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by I-like-stuff** [gdombiak/OctoPod#329]
When using the light theme the device’s status bar i.e where the battery% is is also light and so not very visible. 
![BCCAFC0C-3C3D-4A4F-AC40-E1AD10812639](https://user-images.githubusercontent.com/20486686/82457112-f42f1480-9aac-11ea-90e5-7590d7c4fd14.png)

Also when the theme is set to follow the system’s the top navigation bar remains white in dark mode and in light mode the text is white so not visible.

![6CDB9E5A-D224-4367-A2BD-2D4EEC7DCF4F](https://user-images.githubusercontent.com/20486686/82457100-f2655100-9aac-11ea-8982-1fe7cbdb52e1.png)

**Comment by gdombiak** [comment]
Hi @I-like-stuff,

Thanks for reporting this. My phone has the day, time, wifi bar and battery in black so I never noticed this. I will look for a slightly darker color so contrast looks better. BTW, do you know how I can put those things in white instead of black that my case?

Thanks,
Gaston
