### ISSUE TITLE
FR - An option to allow commands from ios lockscreen

### ISSUE THREAD

**Issue by wikolii** [gdombiak/OctoPod#330]
A cool feature would be to print last file again right from the notification on lockscreen.
I'm thinking a force touch or long press action menu.
It could be customizable and the user acknowledges the risks (anyone could issue these commands without unlocking the phone)

Thanks!

**Comment by gdombiak** [comment]
This is a super cool idea! Marked as an enhancement for a future release.

Thanks,
Gaston
