### ISSUE TITLE
[FR] Display already printed files in a different color

### ISSUE THREAD

**Issue by DominikPalo** [gdombiak/OctoPod#334]
It would be useful to use a different color for already printed or cancelled/failed files in the files explorer (like in OctoPrint UI, where printed files use green text and cancelled/failed files use red text).

See screenshots:
<img width="313" alt="OctoPod" src="https://user-images.githubusercontent.com/1623257/83722045-92d67c00-a63c-11ea-9b64-791096e9bf8e.jpg">

<img width="313" alt="OctoPrint" src="https://user-images.githubusercontent.com/1623257/83722023-86eaba00-a63c-11ea-9920-ff9a2f8c4aa3.png">

**Comment by gdombiak** [comment]
Love this improvement. Will see what information does OctoPrint expose so I can mimic this behavior.

Thanks,
Gaston

**Comment by gdombiak** [comment]
![Screen Shot 2020-06-04 at 10 03 32 PM](https://user-images.githubusercontent.com/1791267/83838845-424c3680-a6af-11ea-93b5-af26143af8b0.png)
