### ISSUE TITLE
OctoPod shows different file sizes

### ISSUE THREAD

**Issue by DominikPalo** [gdombiak/OctoPod#335]
As you can see on the attached screenshot, the sizes of the files displayed in OctoPrint are different when compared to sizes in OctoPtint UI. Not a big deal, I'm just curious. Maybe it is due to a different formula used for the conversion from bytes to MB (SI conversion, where 1 MB = 10^6 B vs binary conversion, where 1 MB = 2^20 B)?

![image](https://user-images.githubusercontent.com/1623257/83722676-b8b05080-a63d-11ea-9cd7-cfee8006ba45.png)

**Comment by gdombiak** [comment]
Wow. That is SUPER weird! :) Could you upload one of those gcode so I can reproduce it locally and fix it?

Thanks,
Gaston

**Comment by DominikPalo** [comment]
Of course, here is it: [F9_Land_Gear_Mount.gcode.zip](https://github.com/gdombiak/OctoPod/files/4731838/F9_Land_Gear_Mount.gcode.zip)
