### ISSUE TITLE
Show Estimated Completion Time on Watch App

### ISSUE THREAD

**Issue by jw59** [gdombiak/OctoPod#341]
Love the watch app but would really love for it to show me the time of completion rather than (or in addition to) the time remaining. 

I tend to run long prints and quickly calculating what time 11h 17m from now is doesn’t really work.  I find myself looking at the watch then grabbing my phone just so I can see the Print Completion time.

**Comment by gdombiak** [comment]
![Screen Shot 2020-06-07 at 9 57 15 PM](https://user-images.githubusercontent.com/1791267/83993976-e7624b80-a909-11ea-8040-f5e2ea2146cb.png)
