### ISSUE TITLE
[FR] Fixed width font in Terminal view

### ISSUE THREAD

**Issue by jpflouret** [gdombiak/OctoPod#349]
It would be nice if the terminal view used a fixed width font. Any kind of formatting of tables gets lost/is hard to read.

**Comment by gdombiak** [comment]
Hi @jpflouret, could you give me an example where I can see the problem? This will help me confirm that the fix solved what you requested.

Thanks,
Gaston

**Comment by jpflouret** [comment]
![FE17F171-D7D2-4FC3-BD6C-D6A0713CDE3C](https://user-images.githubusercontent.com/9397098/91676336-58be2e80-eaf4-11ea-903b-988249374ac5.png)

Notice how the font in the terminal window is not fixed width and thus the repeating text doesn’t align. This is especially bad when looking at a table like the result of M420 V in Marlin.

**Comment by gdombiak** [comment]
Gotcha! That helps a lot! Will see what I can do for the next release.

Thanks,
Gaston

**Comment by gdombiak** [comment]
![Screen Shot 2020-09-12 at 9 40 23 AM](https://user-images.githubusercontent.com/1791267/93000258-10334780-f4dc-11ea-8de9-f5f8273cf8fa.png)
