### ISSUE TITLE
Octopod external network

### ISSUE THREAD

**Issue by DemiDieuAscar** [gdombiak/OctoPod#350]
Hello,
I cannot access my printer outside my local network, but I do receive notifications on the application when the printing is finished.
is it possible to connect in 4G to see the progress of printing?

**Comment by jessearmstrong** [comment]
OctoPod is only able to connect to Octoprint instances on a local network. You can set up a VPN tunnel to your home network and when connected it will work just like if you were at home. I do this and it works great.

**Comment by gdombiak** [comment]
@jessearmstrong is spot on. You can follow [this guide](https://github.com/gdombiak/OctoPod/wiki/Using-OpenVPN-for-Remote-Access) to learn how to setup your VPN. For a less secure option but easier to setup you can use a reverse proxy with authentication and port forwarding.

**Comment by DemiDieuAscar** [comment]
Hello,
Thank you for your answers @jessearmstrong @gdombiak

**Comment by gdombiak** [comment]
Closing this ticket unless there is something to fix in OctoPod.

Thanks,
Gaston
