### ISSUE TITLE
Camera view upside down on iPad

### ISSUE THREAD

**Issue by juchabox** [gdombiak/OctoPod#354]
Hi I use Octopod on iPhone and iPad with the same Octoprint server on Raspberry Pi connected to a single printer.
On the OctoPrint UI I flipped the camera view as it is looking to the print bed upside down. The view on Octoprint UI is correct. It is also correct on OctoPod on my iPhone. But on my iPad, OctoPod show my camera view upside down.

IPad Pro 11in
Ipad OS 14.0
OctoPrint 1.4.0

**Comment by juchabox** [comment]
I close the app and restarted it.
The view is in the correct direction now.
Sorry about the noise.

**Comment by juchabox** [comment]
I closed the app and restarted it.
The view is in the correct direction now.
Sorry about the noise.

**Comment by gdombiak** [comment]
I was going to reply that it is the same code so it was weird. Thanks for updating the ticket with the resolution.

Gaston
