### ISSUE TITLE
404 error accessing websocket ("Not refreshing"/Starscream.WSError) when configured OctoPrint URL ends with /

### ISSUE THREAD

**Issue by cerebrate** [gdombiak/OctoPod#356]
This is not strictly speaking a bug report against OctoPod since it appears to me that the underlying problem belongs to OctoPrint (and therefore there is a full bug report here:

https://github.com/OctoPrint/OctoPrint/issues/3652 )

but for your information, and that of anyone else suffering this error.

**Comment by cerebrate** [comment]
(Not that it would hurt to trim the trailing slash off on the OctoPod side, either, of course.)

**Comment by ariforu** [comment]
@gdombiak this is a known issue we discovered which testing OctoPrint for Mac
