### ISSUE TITLE
Cant add or update printer - save button greyed out and disabled - Display icon/text when app is locked

### ISSUE THREAD

**Issue by dan-glass** [gdombiak/OctoPod#357]
Since upgrading to the latest iOS version 3.5 the "save" button on the "Printer Details" screen remains greyed out no matter what is entered:
 - photo or api  key string
 - http / https
 - enter port number in url
 - ip or host name
 - username valid or missing

The printers entered before upgrading work, but they cannot be modified.

(NOTE: The "scan" function doesn't find anything, so I was not able to test whether that would cause the save button to be enabled)

**Comment by dan-glass** [comment]
Deleting app and settings, and reinstalling fixes issue.

**Comment by kylerw** [comment]
I am experiencing the same thing

**Comment by gdombiak** [comment]
Hey @kylerw ,

Could you share screenshots so I may see what is going on? BTW, after you completed required fields (top 3), let me know if save button is enabled after you tap on any other part of the screen.

Thanks,
Gaston

**Comment by Xalior** [comment]
I too am getting this, and removing and reinstalling the app does not let me add a new printer.  I also cannot delete my old printer, or disable iCloud syncing, meaning new installs of the app contain my old printer.  To be clear I don't want to remove my old printer, I just want to add a second new printer -- but tried to remove the old one as a debugging step.  Have tried to add via App API, OctoPrintEverywhere, and deprecated Global API, on two different iPhones, and the problem is always the same - save button never activated, so could not create new printer.

**Comment by gdombiak** [comment]
Hi @Xalior, sorry to hear the save button is putting up a fight. No need to delete a printer or reinstall the app to make this work. Could you do a simple test to see if this works? Once you completed all required fields (make sure you have a name, hostname and api key if you are using app key or global api key) then tap with the finger on any other field so your last field loses focus. Let me know if save button is enabled after this.

It would help me if you can tell me the exact steps you followed (maybe take a screenshot for each step) so I can reproduce this problem and see how I can fix it.

Thanks,
Gaston

**Comment by Xalior** [comment]
Pick Local Auth:
![15DCFE25-538C-43FF-B6C6-95FBE1D79247](https://user-images.githubusercontent.com/114975/131249322-202b116b-ec73-4426-87af-46cb1141def9.png)
Pick my Printer from the "scan" button:
![E2A28F9B-046E-47FD-AD62-9088ACF0AAB5](https://user-images.githubusercontent.com/114975/131249328-947abead-8515-44a7-94e1-ff4827ade513.png)
Enter username, have even tried creating different user in octoprint:
![F70CC0EA-5D19-4B3B-A770-A016C86EF157](https://user-images.githubusercontent.com/114975/131249351-2c3af9e0-013b-4b7a-815f-9a6db6cce643.png)
Enter password, same credentials work fron from browser:
![F95B9D70-9316-47A2-AE56-0ACB684F2581](https://user-images.githubusercontent.com/114975/131249362-99c388b8-042e-4bad-acc6-ef7379924230.png)

Have tried clicking out of password box, onto other widgets at this point, tried toggling the switches for camera, tried tapping into the empty space in the UI layout, tried tapping the disabled save button, nothing progresses out of this screen except "Cancel".

**Comment by Xalior** [comment]
And, to confirm, the printer connection dialog box does contain correct, sane, details from the Scan...
![53CD5D1A-4C9F-4B31-867B-339C3531CE7F](https://user-images.githubusercontent.com/114975/131249434-78773460-63e6-4ba8-a5b7-3bea65ceb297.png)

**Comment by gdombiak** [comment]
Hi @Xalior,

Thanks for sharing this great info. In this case, I see that you are using "Application Key" for adding a printer. The save button is disabled until you clicked on the **Request** button at the bottom and from OctoPrint you approved the request to give OctoPod an application Key.

However, in your screenshots I see that the **Request** button is also disabled. Since you completed the name of the printer and the URL address, the only reason to have that button disabled is that the app is locked. In OctoPod, could you go to Settings -> Security and make sure that **Lock read-only mode** is disabled?

Gaston

**Comment by Xalior** [comment]
And that has sorted it! 

I can delete old printers too now (which was another “bug” which was bugging me)

I never turned that on (to my memory) and the “lock bit” has synced across all my devices, via iCloud I presume (I do have sync enabled) and lead to a very frustrating week of trying various things, uninstalling and reinstalling, etc!  

Thanks for your help!

**Comment by gdombiak** [comment]
Excellent!! This tells me that I should show some indicator that the app is locked!!! The lock is handy when you are using Apple TV and want to lock print controls or if you handle the phone to someone and you do not want them to mess with your print job.

**Comment by Xalior** [comment]
I concur that it’s a good feature and — while I don’t deny turning it on, I never turned it on intentionally, or consciously — but I’m not saying you have a bug there, but I am wondering when I accidentally engaged that...

The fact I didn’t know it was on, however, has been “the issue” for me for a whole week, and I’ve definitely “wasted" a lot of time trying to debug the situation before contacting you.  

I notice you’ve put a lot of new iconography in the latest build (sorting the printer list, thumbnails in the camera view, etc.) so maybe a new padlock in the printer list on the lower left (opposite side to the sort icon) when the app is in R/O mode would be enough?

-Dx

**Comment by gdombiak** [comment]
How about this idea? I replaced the + button and the Save button for a lock 

![Simulator Screen Shot - iPhone 8 - 2021-08-29 at 14 02 49](https://user-images.githubusercontent.com/1791267/131265361-15ea8b1f-db8f-40b9-8220-15a4514c547a.png)


![Simulator Screen Shot - iPhone 8 - 2021-08-29 at 14 02 54](https://user-images.githubusercontent.com/1791267/131265362-8736e178-8c56-4da5-a55f-4223488c6caf.png)

**Comment by Xalior** [comment]
Much better idea ;-)

**Comment by gdombiak** [comment]
Excellent. Will go with this then for the next release. Thanks @Xalior for the feedback
