### ISSUE TITLE
iOS 14 local network access permission

### ISSUE THREAD

**Issue by webpty** [gdombiak/OctoPod#359]
### Update: 
Can't connect? Make sure to grant local network permission to the app

> Settings > privacy > local network > OctoPod [ on ]

---
I've recently updated my iPhone 7+ to iOS 14 beta, and i get an error. That being said. it's not a production version so I dont pretend everything is going to be working flawlessly. I thought i'd let you know, though...
I currently get this message: 
```"the internet connection appears to be offline"```

Clicking on the  camera stream link does open the camera link, but I have no control over the printer.

My iPad which is on the latest iOS 13 production version still works beautifully.

![IMG_1559](https://user-images.githubusercontent.com/11739306/89931011-3a3dd500-dbd1-11ea-955a-a811de493779.PNG)

**Comment by gdombiak** [comment]
Hi @webpty 

Thanks for bringing this up to my attention. I haven't tested the app with the new iOS 14 yet. I will see if I can reproduce this issue. BTW, does it work fine if you are not using VPN?

Thanks,
Gaston

**Comment by webpty** [comment]
Hi @gdombiak,
I actually had not checked that, but removing it did not make a difference.
Thanks!

**Comment by webpty** [comment]
Hi @gdombiak 
I found out it was just a permission issue.
As it is a permission automatically granted previously, and not on iOS13, it makes sense that Octopod doesn't ask for it.
Permission found in `Settings > privacy > local network`


![IMG_1564](https://user-images.githubusercontent.com/11739306/89942706-a70d9b00-dbe2-11ea-89e0-eafcd288b88f.PNG)

![IMG_1563](https://user-images.githubusercontent.com/11739306/89942550-63b32c80-dbe2-11ea-88a1-f70b9bc16d80.PNG)

**Comment by jessearmstrong** [comment]
You mean you don't want Facebook to be able to access your local network!?

</s>

**Comment by webpty** [comment]
I think the wording i've seen on the dialogs is something like 
> Do you want to allow FB to look for devices on your network?

Thanks, but no thanks

**Comment by gdombiak** [comment]
Thanks guys for tracing OctoPod more than Facebook app. hahahaha :D

**Comment by gdombiak** [comment]
Great finding @webpty. You just saved me some time researching what was going on. Seems to be a very easy fix.

**Comment by gdombiak** [comment]
![IMG_1803](https://user-images.githubusercontent.com/1791267/90325089-2e814400-df2c-11ea-9b30-06c0e6540e97.png)

Fixed and tested on iOS 14 Beta 4. 

Thanks for reporting this!
Gaston

**Comment by gdombiak** [comment]
@webpty & @jessearmstrong, I created a new beta version for the next release that includes this fix and the Siri one that Jesse reported and many other things I worked over the weekend. Let me know if you guys are interested in being part of the beta testing team. Send me an email to gdombiak at gmail.

Thanks,
Gaston

**Comment by jessearmstrong** [comment]
I’d be happy to help beta test. Anything you need!

**Comment by webpty** [comment]
@gdombiak Of course! count me in!

**Comment by gdombiak** [comment]
Excellent guys! Send me an email to the address I shared above. Once Apple approved the new beta I will share the link with you. You will need to install TestFlight app if you do not have it already.

Thanks,
Gaston

**Comment by Neokamikaze** [comment]
Hello, I have the same problem (my phone is Iphone 12 on iOS 14.4.2). Access to the API from a Chrome interface is very fast but from the application it is impossible to retrieve the print data.
Thanks
