### ISSUE TITLE
Siri suggestions should not include cancelling a print

### ISSUE THREAD

**Issue by jessearmstrong** [gdombiak/OctoPod#361]
I managed to cancel a print job today about 13 hours in because an OctoPod notification popped up (I don't even know what it was for, probably 50% announcement) and when i went to click on it there was a siri suggestion on the screen to instantly cancel my print. Which I tapped on by accident and instantly canceled my print. No confirmation warning or anything. I think canceling a print should be a more restricted thing that always require confirmation. I don't siri should be able to do it. I would hate for siri to activate accidentally and misunderstand me to cancel a print either. I don't know that I could reproduce it, but it was not fun.

**Comment by gdombiak** [comment]
Ouch! That sucks! Sorry that happened @jessearmstrong. Since this action is done via Siri, I'm not sure I can add a confirmation prompt to confirm the action. I will look into that option and if not then see of not donating that action. Maybe via a setup configuration.

**Comment by gdombiak** [comment]
![IMG_1804](https://user-images.githubusercontent.com/1791267/90325521-78b8f400-df31-11ea-9144-7356cf7f64a0.png)

**Comment by gdombiak** [comment]
I'm not sure if change in configuration applies to already existing shortcuts. Might need to delete shortcut and create it again. Or maybe delete the app and recreate shortcuts. In my test I delete the app and things worked. Did not test before deleting the app. :(
