### ISSUE TITLE
I get 2 notifications for everything. How do I change that?

### ISSUE THREAD

**Issue by darrenph1** [gdombiak/OctoPod#366]
For some reason I started getting 2 Notifications for everything. Is there a way to stop this?
![IMG_5CDF6F2228C7-1](https://user-images.githubusercontent.com/35897899/92332094-f2736780-f02f-11ea-9e99-2d47e79b85fb.jpeg)

**Comment by gdombiak** [comment]
Hi @darrenph1,

My guess is that somehow you ended up with duplicated entries in your plugin configuration. Do the following to confirm if this is your case:
1. ssh into your octopi box (I'm assuming you are using octopi)
1. cd .octoprint
1. Edit config.yaml and go to plugins: -> octopod -> tokens
1. You should see an entry for each combination of printer and iOS device. If you have duplicates you will see more entries than you expected
1. Feel free to delete all tokens and restart both OctoPrint and OctoPod app. OctoPod will register with new tokens again

People that tried to spawn a new OctoPrint instance by doing a backup and restore of the configuration are the ones that ended up duplicating entries. Not sure if that was your case. There is a ticket to show in OctoPrint UI the list of registered tokens so you can manage them from there.

Hope this helps,
Gaston

**Comment by darrenph1** [comment]
Thanks, I could never find where the location is via the GUI but via ssh I
found the tokens and deleted them. I'll know in about 6 hours if it worked
but sound like it should. I noticed the " - " that you mentioned also in
other plugins I have. I guess that means I have duplicates for those as
well.  I should be able to delete those also, yes?

Thanks for your help and the great app!!

Darren

**Comment by gdombiak** [comment]
@darrenph1 , remember that a restart of OctoPrint and also of the OctoPod app are going to be needed for the changes to make effect and have the phone registered to receive notifications from the plugin.

The "-" that you see in that file means that the property (e.g. tokens) has many values. Under "plugins" you also see that each entry has a "-" which means a value of the list of plugins. In [yaml this is called a collection](https://www.tutorialspoint.com/yaml/yaml_collections_and_structures.htm).

**Comment by darrenph1** [comment]
That fixed the issue. Thanks!

**Comment by spartan152** [comment]
I'd like to re-open this as I was not able to resolve this. I only see one token in my config.yaml file, although I have restored from a backup a couple times. Should I try to delete the token and set it up fresh?

**Comment by gdombiak** [comment]
Hi @spartan152, the instructions on this ticket are no longer necessary. You can now use your browser to go to OctoPrint's settings. Go to the OctoPod Notifications page and click on Devices. That page shows all the devices that are registered with that OctoPrint instance. You can click on the trash icon to delete any device you no longer want to be notified. If you delete all the entries then open the OctoPod iOS app and it will register again.

Hope these instructions help.
Gaston

**Comment by macochran** [comment]
I am getting two notifications as well, but I only have one device listed in the settings.  I have deleted that device and re-registered, and I'm still getting two notifications.  Any ideas?

**Comment by gdombiak** [comment]
Have you tried following the instructions of the message above yours? My guess is you have multiple devices (that point to your same phone)

**Comment by macochran** [comment]
Yes. Under settings is where I can see that only one device is listed. It's also where I deleted the device, and see that only one device was re-registered. 

Edit:  Odd.  I didn't make any changes recently, but today I'm only getting one notification.

**Comment by macochran** [comment]
It appears very random.  I've been printing all day, and receiving single notifications, but I just received a double.  Even on the same print... I got a single notification that layer 2 was complete, and a single notification for 25%, but a double for 50%.  Strange.
