### ISSUE TITLE
Port to Android?

### ISSUE THREAD

**Issue by bdelia** [gdombiak/OctoPod#377]
I love the idea of this project, but I am not a iPhone, iPad user and was wondering if there has been any consideration for porting to the Android platform.  I'd even be interested in contributing.

**Comment by gdombiak** [comment]
Hi Brett!!!! :)

I think that some people tried running Swift in Android but iOS frameworks/libraries are not present in Android. This basically means that the app would need to be rewritten to run in Android. I heard many good things about [Printoid](https://printoid.net/) and their UI looks way cooler than OctoPod. :) They have a free version and a pro version from what I see.

Best Regards,
Gaston
