### ISSUE TITLE
What should be in Widget View? 

### ISSUE THREAD

**Issue by amodernstitch** [gdombiak/OctoPod#378]
Should I see the actual camera running or a placeholder. This is what I see in the widget. 
![IMG_0163](https://user-images.githubusercontent.com/58535555/94498200-2c630400-01bf-11eb-89b0-5c78759efc1f.jpeg)

**Comment by gdombiak** [comment]
Hi @amodernstitch, you will have to long press on the widget and select "Edit Widget". Select the camera you want to see and you are good to go. I was not able to make it auto-select a camera when you install the widget so this manual step is needed.

Let me know if that helped.
Thanks,
Gaston

**Comment by amodernstitch** [comment]
Sorry if I missed those instructions. Works great! Thanks, m
