### ISSUE TITLE
iOS 14 Widgets Open to Last State

### ISSUE THREAD

**Issue by Willmac16** [gdombiak/OctoPod#402]
When I open the app from an iOS 14 widget or notification, the last printer I was viewing appears instead of the printer the notification/widget was for. I believe that the old (pre iOS 14) widget opened to the selected printer.

**Comment by Willmac16** [comment]
It looks like the medium widget didn't have its url set. I created a pr #403

**Comment by gdombiak** [comment]
PR merged. Thanks @Willmac16
