### ISSUE TITLE
Add Siri Shortcuts to control Enclosure plugin switches

### ISSUE THREAD

**Issue by JoachimBates** [gdombiak/OctoPod#406]
First off, 

Your app is truly flawless and well through out. It’s polishes off the entire seamless idea that octoprint encompasses. I’ve searched around the net but can’t seem to find if it’s possible to create custom Siri Shortcuts? I’d like to be able to “switch lights off/on” through the Enclosure plugin and the likes. 

Thanks 
Joe

**Comment by gdombiak** [comment]
Hi Joe,

Thanks for suggesting this improvement. Is this only about being able to ask for enclosure status of INPUt and OUTPUT and to be able to turn on/off an OUTPUT of the Enclosure plugin? I can explore adding support for those things. Let me know if you had other Siri shortcuts in mind.

Thanks,
Gaston
