### ISSUE TITLE
Very high data usage over cellular

### ISSUE THREAD

**Issue by BlaydeRunner08** [gdombiak/OctoPod#408]
I recently noticed that I'm noticing that OctoPod seems to take an incredible amount of cellular data.

Typically, I used OctoPod to keep an eye on my print while I'm on the same wifi, but occasionally I use it to monitor it remotely.  Usually, when I'm out, I'll open the app, check the print/webcam, and then turn my phone off.  However, I just went to check my data usage, and I noticed that OctoPod used up 2GB in the last month!!!

Does the app continue to run the webcam stream even when it's running in the background?  Has anyone else experienced this? 

![Here's a screenshot of the data usage](https://user-images.githubusercontent.com/25095784/97793175-ad8a2e00-1ba5-11eb-9559-bb0770d2136b.PNG)

**Comment by gdombiak** [comment]
Possibly good news. While adding HLS support to OctoPod I noticed that (at least in the Simulator) the websocket connection remains active when the app goes to background. iOS should have stoped network traffic but it did not at least when using the simulator.

I added code so that the app closes the websocket connection when it goes to background to make 100% sure that there is no more traffic.

**Comment by BlaydeRunner08** [comment]
That’s great to hear! Thanks for all your work!

**Comment by gdombiak** [comment]
@BlaydeRunner08, are you using the Apple Watch app? Are you using OctoPod with multiple printers?

I fixed a few more cases where there is network traffic when changing selected printer from Apple Watch. And even more if you have a camera configured. I now see zero network traffic after the last fixes

**Comment by BlaydeRunner08** [comment]
@gdombiak Yes to the Apple Watch, but no to the multiple printers.

**Comment by gdombiak** [comment]
@BlaydeRunner08, I'm curious to hear if the new release actually fixed the high data usage you observed over cellular.

Thanks,
Gaston

**Comment by BlaydeRunner08** [comment]
Hey @gdombiak,

yeah, it looks muuuuuch better. These are my cellular stats, last reset around the time the new release:
![4409E232-E7FE-466B-9F28-D870C9E52E16](https://user-images.githubusercontent.com/25095784/104853712-74657e00-58b7-11eb-9827-56980c6c8548.jpeg)

Thanks again!

**Comment by gdombiak** [comment]
Sweet! That's great to hear. Good to confirm our wild guess hit it on the head. :)

Thanks,
Gaston
