### ISSUE TITLE
I can’t add my printer

### ISSUE THREAD

**Issue by renegadecitizen** [gdombiak/OctoPod#410]
I’m trying to add my printer
I’m using octoprintanywhere
I scan the code
But it gives me the connection error 
The operation couldn’t be completed 
(Starscream.WSError error 1)

Could you please help me?

**Comment by gdombiak** [comment]
Hi @renegadecitizen,

Are you using https or http to connect to OctoPrint? If you are using https and you are not using a valid certificate ... then this error means that the presented certificate is not valid. If you want to use https with not a valid certificate then go to OctoPod -> Settings -> Security and disable certificate validation.

Let me know if that helped or if you are not using https.

**Comment by renegadecitizen** [comment]
I tried it
It didn’t help 
It gives me a warning 
It couldn’t connect because it’s not in the correct format 

Thanks for helping man

**Comment by gdombiak** [comment]
Could you share the warning that you got and the incorrect format message that you got? That might help troubleshoot this issue.

Thanks,
Gaston

**Comment by renegadecitizen** [comment]
![4EC80F4F-4A81-48D8-8F5E-F5DB6F9D9E44](https://user-images.githubusercontent.com/6202311/100150533-fc517d80-2e5c-11eb-94b9-a9425464780b.png)
![02B82072-84F9-41F1-AF67-E4FB34AF2641](https://user-images.githubusercontent.com/6202311/100150542-ffe50480-2e5c-11eb-81f9-ea55c5e1fd9f.png)

These are the two errors I’m getting 
It’s not a local installation 
My Pi is located at
https://renegadecitizen.octoeverywhere.com

**Comment by gdombiak** [comment]
How does thing work when you are in the local network? If they work fine, then we should take a look at your reverse proxy (I'm assuming you are using one). Are you using a VPN or port forwarding? Could you share more about your setup.

Regards,
Gaston

**Comment by renegadecitizen** [comment]
It works fine on local
Neither VPN or port-fowaring
Only octoeverywhere.com
I understand if it doesn’t work with your app

**Comment by gdombiak** [comment]
Gotcha. I checked out that product and he developer is slowly adding support for apps. Check out [this link](https://www.reddit.com/r/OctoEverywhere/comments/jy08e5/octopod_support/). I think he also mentions that on his website

**Comment by renegadecitizen** [comment]
Cool they mention octopod so there’s hope

**Comment by gdombiak** [comment]
Will close this ticket for now. Let me know if you need any further help.

Gaston
