### ISSUE TITLE
Configured camera feed for iPad Air 2020 & iPhone 12 series

### ISSUE THREAD

**Issue by pixelmagic66** [gdombiak/OctoPod#414]
On my older iPad Air 2 I get a camera stream above the printer status on the first page, but aomehow with the exact same settings on the Air 2020 no camera feed, just the printer status. Even side by side checked the settings, deleted from Icloud and new config the same result.

Any clues on how to fix it ?

**Comment by gdombiak** [comment]
That is indeed very weird. Hardware should be indifferent to the app. I will test it on the simulator (I do not have that hardware with me) and will report back.

One thing to check but I'm 100% sure it is not related: Go to iOS Settings -> OctoPod and check that settings are the same. Maybe for some reason Local Network is not enabled in the Air 2020?

**Comment by ssnyder30** [comment]
This also doesn’t work for me in landscape orientation on an iPad Air 2020. However it does work in portrait orientation. Rotate the iPad one way, camera feed is visible, rotate it the other way, and the camera feed disappears.  I suspect this has to do with the sizing of UI elements to stretch to fill the screen on rotation. Perhaps the Air 2020’s resolution is involved?

**Comment by gdombiak** [comment]
This info helps a lot to troubleshoot this. Will add it to the next release since I might have an idea on what is going on. Thanks @ssnyder30 for the extra info.

**Comment by pixelmagic66** [comment]
I can confirm that it works in portrait mode and not in landscape on the Air 2020
