### ISSUE TITLE
Auto-lock job buttons based on iOS configuration

### ISSUE THREAD

**Issue by GethSibbons** [gdombiak/OctoPod#420]
Is there any way to disable the pause/cancel option for the Apple TV app and just show the camera and I for only? Kids keep trying to cancel prints.

**Comment by gdombiak** [comment]
Scheduled for next release (after I release the one I'm wrapping up). Thanks for the idea!

**Comment by gdombiak** [comment]
The app will now follow your settings of your phone. If you lock the app from the phone then the Apple TV will disable buttons that impact the print job. I also added new confirmation dialogs that you can control from the app and the Apple TV will follow your iOS configuration.
