### ISSUE TITLE
Text color in Light Theme and Dark Mode

### ISSUE THREAD

**Issue by simonbogh** [gdombiak/OctoPod#426]
Hi,

When the theme is set to Light, and your phone switches to Dark Mode, then the text you write to set the extruder and bed temperature becomes white text on white background. 
![image](https://user-images.githubusercontent.com/10414639/101792106-9aec0880-3b04-11eb-99eb-6ba9feac3504.png)
![image](https://user-images.githubusercontent.com/10414639/101792119-a0495300-3b04-11eb-8889-6f512aeff550.png)

**Comment by gdombiak** [comment]
Thanks so much @simonbogh for opening this issue. Themes have been around for a long long time and I had no idea we had this issue. :)

It is now fixed for the next release coming out in a few days.

Thanks,
Gaston

**Comment by simonbogh** [comment]
My pleasure, and happy to see the quick fix 😊
