### ISSUE TITLE
Please i need PSU Plugin into the app

### ISSUE THREAD

**Issue by fadi9696** [gdombiak/OctoPod#430]
Please i need PSU Plugin into the app to turn printer off and on

**Comment by gdombiak** [comment]
Hi @fadi9696 , here is the list of [supported plugins](https://github.com/gdombiak/OctoPod/wiki/Supported-Plugins). PSU Control is supported. Are you asking for that plugin?

**Comment by fadi9696** [comment]
Yes i'm asking for PSU plugin its on the list but how to show it on app?

**Comment by gdombiak** [comment]
The steps would be:
1. Install [PSU Control](https://plugins.octoprint.org/plugins/psucontrol/) plugin in OctoPrint
2. Open OctoPod
3. In the main window (Panel) you can swipe from right to left and you will see more subpanes. You will see the temp graph pane and as you swipe more then you will see the PSU Control pane

Hope that helps,
Gaston

**Comment by fadi9696** [comment]
Thank you so much you are awesome

**Comment by gdombiak** [comment]
Let me know if we can close this ticket now. BTW, all other plugins work in a similar way. You swipe and you access more and more functionalities

**Comment by gdombiak** [comment]
One last ask: Please leave your app review if you haven't given one already. This helps spread the word and help other people find the app. Thanks

**Comment by fadi9696** [comment]
I totaly did'nt knew about this awesome feature, i will leave a review about it, thank you again

**Comment by gdombiak** [comment]
Closing the ticket for now. Let me know if you need further assistance.

Gaston
