### ISSUE TITLE
Add custom default temperatures

### ISSUE THREAD

**Issue by MunchHansen** [gdombiak/OctoPod#440]
It would be great - if it was possible to change the default temperatures shopping jo when setting the temperature for either the end or bed.

**Comment by gdombiak** [comment]
Hi @MunchHansen,

OctoPod should render the temperatures that you defined in OctoPrint. Have you set them here?
![Screen Shot 2021-01-05 at 11 23 01 AM](https://user-images.githubusercontent.com/1791267/103689675-7be86700-4f48-11eb-9544-88ad675ab179.png)


Regards,
Gaston

**Comment by MunchHansen** [comment]
Hi Gdombiak.

My bad sorry and thanks for showing me! I had not discovered that option!

Have a nice day.

**Comment by gdombiak** [comment]
Cool. I will add it to the [FAQ](https://github.com/gdombiak/OctoPod/wiki/FAQ-using-the-app). I'm sure other people have the same question.
