### ISSUE TITLE
BL Touch Commands in Octopod

### ISSUE THREAD

**Issue by bkarr123** [gdombiak/OctoPod#451]
Would there be a way to add the BL Touch commands (i.e. Probe Up/Down) into the Move tab of Octopod on iOS? I see a bunch of commands, but BL Touch commands would be great since I have to test probe my needle since it will crash into the bed if I don't do that.

**Comment by gdombiak** [comment]
Thanks for sharing this idea. I'll see what I can do. I'm not aware of a way to detect if a printer has bl touch or not (one of my printer has it while the other don't) so ideally this new feature should only appear if it has bl touch.

Thanks,
Gaston

**Comment by bkarr123** [comment]
<img width="630" alt="Screen Shot 2021-01-29 at 7 23 54 PM" src="https://user-images.githubusercontent.com/76626217/106342752-c3bc8e80-6267-11eb-9dbd-f39c83a00102.png">

Thanks! These are the commands I was looking for, the row of BL Touch commands at the bottom. Those actually populate in my Octoprint control because I also have the BL Touch plugin on my Octoprint instance.
