### ISSUE TITLE
Enhancement: Search in file list

### ISSUE THREAD

**Issue by jessearmstrong** [gdombiak/OctoPod#459]
Hey Gaston,

Octoprint web interface has a little type ahead search blank in the file list. I do often print old gcode and use that search list with some frequency to find one of those older files. I would love to have the type ahead search in the OctoPod file list. not sure how much effort is required but it would be nice to have.

**Comment by gdombiak** [comment]
Hey Jesse,

I can squeeze in this feature for the next release. I think it is a very convenient feature.

Thanks,
Gaston

**Comment by gdombiak** [comment]
https://user-images.githubusercontent.com/1791267/107128302-79439f00-6871-11eb-9209-ccf0b036343d.mov
