### ISSUE TITLE
Save the "Suppress temp/SD" state between sessions

### ISSUE THREAD

**Issue by DBa2016** [gdombiak/OctoPod#460]
Right now, whenever I start Octopod, the "Suppress temp messages" in terminal is off, so the terminal is flooded. Looking for a particular message there is just impossible. 
It would be great to either make the default state configurable in settings (probably too much of an overhead) or just save the last state so that the next time you open the app, the temp messages are suppressed (or shown - according to personal preference).

**Comment by gdombiak** [comment]
Hi @DBa2016, I will add this small improvement to the next release so it remembers (locally) the last setting. I'm assuming that you are killing the app. 

Gaston
