### ISSUE TITLE
Camera feed fails to update live when launching app from widget

### ISSUE THREAD

**Issue by AudioBr4in** [gdombiak/OctoPod#474]
Hello again,

Very minor bug, but wanted to point it out just in case.

When launching the app via the widget, the camera feed stays frozen with the frame that was seen in the widget and doesn't actually update back to live until switching tabs (thus refreshing the view). 

![image](https://user-images.githubusercontent.com/69870988/110763352-a2f03d00-8206-11eb-91b7-988d1a044fc6.gif)

Update: the same behavior occurs when opening the app from a notification.

**Comment by luco85** [comment]
Same problem after last update here
