### ISSUE TITLE
Spool manager integration

### ISSUE THREAD

**Issue by luco85** [gdombiak/OctoPod#475]
Hi! I use the spool manager plugin but is not seen in octopod. Is possible to integrate it in to the app? Thanks

**Comment by BlaydeRunner08** [comment]
Hey @luco85, are you talking about the FilamentManager plugin?  If you are, it is supported.  If you swipe over to the third page on the "Panel" tab, you'll see the relevant information.

That being said, I have asked @gdombiak in #472 to add a bit more functionality for the plugin.

**Comment by luco85** [comment]
Hi! Yes i know filament manager, i used it with octopod, but i mean about spool manager, another plugin from same developer

**Comment by samwiseg0** [comment]
I too would like to see this integration. Here is a link to the source repo for reference https://github.com/OllisGit/OctoPrint-SpoolManager

**Comment by kadaan** [comment]
Would someone want to try to get this into PR form and submitted to this repo?  I don't have time.

https://github.com/gdombiak/OctoPod/commit/0a91f173c0986b758ae1dba7cedf13021c45a51c

**Comment by gdombiak** [comment]
Hi @kadaan ,

Thanks again for yet another contribution. My feedback here is similar to your other contribution:
1. Could you export the changes somehow so I can process them easier?
2. What are the changes in the data model? (eg. anything else besides adding 'spoolManagerInstalled' to Printer?)
3. What's new in the UI? (I assume a VC to let people select their spool)
4. Want to confirm whether you added support for alerting user when there is not enough filament in the spool before print start.

Thanks again,
Gaston

**Comment by kadaan** [comment]
1. I will try to find time of XMas
2. Correct, just `spoolManagerInstalled` was added to `Printer`
3. Basically a copy of the Filament UI with some slight changes, one of which is the showing the code from SpoolManager.  The code is useful because it can help you ensure you pick the spool the corresponds with the UI
4. I did not

**Comment by kadaan** [comment]
@gdombiak #672

**Comment by gdombiak** [comment]
Thanks @kadaan . This PR and your other PR have now been merged (using other PRs)
