### ISSUE TITLE
Printer dashboard scroll bug

### ISSUE THREAD

**Issue by deharren** [gdombiak/OctoPod#481]
First off great app!!  I wanted to report a hug that if you have enough multiple printers in “Printer Dashboard” view then the bottom one that extends off the screen in portrait mode will not all you to view the very bottom. 

It you scroll it down It starts to quickly climb up the screen and cut off the bottom few lines of the detailed results.  Landscape mode works fine though.  See attached video.  Thanks!!

**Comment by tideline3d** [comment]
+1 on this one, annoying on the non-home button iOS devices as the swipe up gets in the way.

**Comment by gdombiak** [comment]
Found the root cause. Testing before adding it for next release. Thanks guys for pushing to get this bug fixed. I thought it was above my skills to get it. :D

**Comment by tideline3d** [comment]
Sweet!  I was considering just adding a dummy printer to the bottom of my list to get around it 👍
