### ISSUE TITLE
I am not able to delete printers from the app. Can not add printers from outside local sources.

### ISSUE THREAD

**Issue by psdavidson812** [gdombiak/OctoPod#482]
Hi, I am not able to delete printers from the app. Can not add printers from outside local sources. ip and port number is good because I can open it in my browser. Thanks

**Comment by gdombiak** [comment]
Hey @psdavidson812 , to delete a printer go to Settings -> Printers and on the printer you want to delete do a slide to the left. You will see a red button for deleting the printer. You can add printers outside of your LAN via OctoEverywhere, VPN or port forwarding + reverse proxy for minimal security.

**Comment by psdavidson812** [comment]
Nope it does not give an option and will not slide. iPhone 12

**Comment by gdombiak** [comment]
What do you think of this idea of seeing a lock when the app is locked and you try to add a new printer or save changes of an existing one?

![Simulator Screen Shot - iPhone 8 - 2021-08-29 at 14 02 49](https://user-images.githubusercontent.com/1791267/131265408-be91258d-ccfe-43a0-a079-a95488bfa8ef.png)



![Simulator Screen Shot - iPhone 8 - 2021-08-29 at 14 02 54](https://user-images.githubusercontent.com/1791267/131265409-a02c6065-294e-4fb6-9f98-8676a1c622fb.png)

**Comment by psdavidson812** [comment]
I really think that would be helpful. It would also give a visual in case
you wasn’t sure what was going on. You could say hey it must be locked let
me look somewhere in the settings.
