### ISSUE TITLE
Feature request - Receive image from camera with shortcut

### ISSUE THREAD

**Issue by jon-daemon** [gdombiak/OctoPod#489]
I use the shortcuts for "resume", "pause" and "time left" and I have added them as widgets on my home screen.
Would that be possible to have another shortcut that will return a still image from the camera? It would be helpful to have a quick progress view without reloading the camera stream.

**Comment by gdombiak** [comment]
Wow. Very cool feature. I will see if that is possible with shortcuts and implement it. Love it!
