### ISSUE TITLE
Enclosure Temp Control - Enclosure Plugin

### ISSUE THREAD

**Issue by Kiwistylebuild** [gdombiak/OctoPod#491]
I have the Enclosure plugin (4.13.1) and Octopod (3.11) is showing the temp/humidity values on the first page and then the LED on/off control the third screen over.  However, I cannot find a control for the enclosure temp feature.  

I had a good look through the other issues and requests which talk about showing the temp values, and controlling the GPIOs around versions 4.2ish but nothing specific on enclosure temp adjustment.  Was this a feature that should already be working, or is it possible to have it added?

Thanks!
Philip

**Comment by Kiwistylebuild** [comment]
That is awesome thanks Gaston.  Yeah main reason I (and probably others) use the enclosure plugin is for the active chamber heating ability, other than to switch a bunch of other stuff just on or off. I just chuck in a target temp and have a couple of ceramic heater in the enclosure that get it up to temp pretty quick.  Its very useful for all the big stuff. 
Cheers!
Philip

![enclosure plugin](https://user-images.githubusercontent.com/84456466/118890793-efba5900-b8c4-11eb-8383-1eb8b160577c.png)

**Comment by gdombiak** [comment]
![Screen Shot 2021-07-21 at 11 19 38 PM](https://user-images.githubusercontent.com/1791267/126597163-6190e129-6511-44c9-9803-52929899862c.png)

Improved PWM and added support to control temp/humidity control outputs.
