### ISSUE TITLE
Feature Request - Grid View of Cameras

### ISSUE THREAD

**Issue by destinybonavita** [gdombiak/OctoPod#495]
It would be awesome to be able to view the cameras of multiple printers at once in a zoom-like grid view.

**Comment by gdombiak** [comment]
Great idea. Will try adding this to the next release. Thanks for sharing this idea.

Gaston

**Comment by gdombiak** [comment]
Slowly coming along!!!

![Screen Shot 2021-07-03 at 2 17 51 PM](https://user-images.githubusercontent.com/1791267/124367139-89d22880-dc09-11eb-81e3-e52b14430fa2.png)

**Comment by destinybonavita** [comment]
That looks awesome!

**Comment by OliS1975** [comment]
I read from the release notes of version 3.12 that the grid view is available now. But where can I activate it?

**Comment by gdombiak** [comment]
Hi @OliS1975 ,

If your OctoPrint installation has [MultiCam plugin](https://plugins.octoprint.org/plugins/multicam/) installed and configured then you should see a new icon at the top-left of the window. See images below:
![Simulator Screen Shot - iPhone 8 - 2021-08-28 at 09 34 05](https://user-images.githubusercontent.com/1791267/131224707-497b2373-814d-4a64-a965-a6e08e5c1529.png)

And this is how it looks when you clicked there. You can rotate the phone for better inspection. You can zoom in/out as well.
![Simulator Screen Shot - iPhone 8 - 2021-08-28 at 09 34 18](https://user-images.githubusercontent.com/1791267/131224721-e8c2af3a-a229-4f5c-a2cd-e9b123896f94.png)

**Comment by OliS1975** [comment]
Thank you for the explanation. So it's for a single octoprint instance with multiple cams. Not for all cams from different octoprint instances?

Oli

**Comment by gdombiak** [comment]
Hey @OliS1975 , that is correct. I will be adding support for watching cameras in the printers dashboard for the next release. I remember there was an issue where someone posted a nice UI design for this but cannot find it. :(

Gaston

**Comment by OliS1975** [comment]
Great to hear. 
In the meantime I installed the multicam plugin and added the cam stream from the second printer to the first one and vice versa. This works as described.

Regards
Oli

**Comment by gdombiak** [comment]
Nice workaround!! :D
