### ISSUE TITLE
Can‘t Connect; Invalid URL

### ISSUE THREAD

**Issue by Tamperold** [gdombiak/OctoPod#502]
Hi,

i have  a issue/bug called Invalid URL. I have two printer on the same octoprint with different URL. 
The invalid URL: http://0.0.0.0:00/CR10S/
and http://0.0.0.0/ANY/
With the app Printoid i was getting the Same issue but the developer fixed thise problem. 

Is there a change to fix thise?

thx for your help and have a nice weekend!

best regards 

Chris

**Comment by gdombiak** [comment]
So appending something after the hostname (e.g. CR10 or ANY in your examples) says this is an invalid URL? Thanks for reporting this. Quick fix that can be added to next release.

Thanks,
Gaston
