### ISSUE TITLE
Enclosure temperature/humidity not showing

### ISSUE THREAD

**Issue by webdeck** [gdombiak/OctoPod#503]
I have the Enclosure plugin installed and the temperature and humidity values show in OctoPrint, but not in OctoPod.

OctoPrint:

<img width="1120" alt="Screen Shot 2021-07-20 at 8 58 18 PM" src="https://user-images.githubusercontent.com/5542961/126428690-6b43b34e-ed69-4e4c-95c2-c0cb522119a4.png">

OctoPod:

![image](https://user-images.githubusercontent.com/5542961/126428748-09781af0-e833-43df-8fd3-4a65c2f9dfb6.png)

Linux octopi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l
OctoPi 0.18.0
OctoPrint 1.6.1
OctoPod plugin 0.3.2
OctoPod iOS App v3.11 build 2

**Comment by gdombiak** [comment]
Hi @webdeck,

Are you using latest version of Enclosure plugin? If not could you update and let me know if that solved it. Assuming you are using latest version ... I tried a lot to reproduce this and was not able to reproduce it. :( So I will ask for some more information to see if we can figure out what is going on.

Could you enable logging of temperature by first enabling **Enable debug info**, then save and then enable **Enable temperature debug info**. It will look like this:
![Screen Shot 2021-07-20 at 11 02 33 PM](https://user-images.githubusercontent.com/1791267/126439410-52af774b-d780-4358-b430-4acb10d6d534.png)


After that you will need to enable debug log like this:
![Screen Shot 2021-07-20 at 11 03 46 PM](https://user-images.githubusercontent.com/1791267/126439440-d77cd944-96cd-40a9-b4f5-ba72479dd317.png)


Last 2 steps:
1. Do you see any error in enclosure plugin logs or OctoPrint logs?
2. Could you paste the debug information that is now printing? You should see things like this

```
2021-07-20 23:06:20,080 - octoprint.plugins.enclosure - DEBUG - Sensor Input 1 Temperature: 39.5 humidity 39.5
2021-07-20 23:06:30,087 - octoprint.plugins.enclosure - DEBUG - Sensor Input 1 Temperature: 40.0 humidity 40.0
```

One more test, if you kill OctoPod app and open it again, does it consistently not show enclosure temp?

Thanks,
Gaston

**Comment by webdeck** [comment]
Thanks for the debugging tips.  I was able to determine that the adafruit_dht.py script isn't working.  It was working at one point, which is probably why the web page is showing temp and humidity values, but they are old.  I'm not sure why it stopped working, but it sounds like a hardware issue.  When I run a test program, I get this error:

RuntimeError: DHT sensor not found, check wiring

**Comment by gdombiak** [comment]
Yep, sounds like a hardware issue. Good that logs helped you find the root cause.

Good luck,
Gaston

**Comment by webdeck** [comment]
To close the loop on this - it was a hardware issue.  I swapped out the DHT22 sensor and it is working agin.  Thanks again.
