### ISSUE TITLE
not able to delete printers or add printers from outside local sources

### ISSUE THREAD

**Issue by psdavidson812** [gdombiak/OctoPod#510]
Hi, I am not able to delete printers or add printers from outside local sources. ip and port number is good because I can open it in my browser. Thanks

**Comment by gdombiak** [comment]
Hey @psdavidson812 , are you still seeing this issue? What do you mean by local sources? Is it your local network?

**Comment by psdavidson812** [comment]
Yes, I am not able to delete my printer nor am I able to edit printers.

**Comment by gdombiak** [comment]
Could you check under Settings -> Security that read-only is disabled?

**Comment by psdavidson812** [comment]
Bingo that was it!!!    Thanks that’s been driving me crazy!!

**Comment by gdombiak** [comment]
Excellent! Another person just run into the same issue. I will improve the UI to give a hint about what is going on so users can troubleshoot this by themselves. Thanks for helping troubleshoot this.

Gaston
