### ISSUE TITLE
Unable to save printer detalis

### ISSUE THREAD

**Issue by 3DStyle** [gdombiak/OctoPod#517]
Hello,
I try to edit a printer detalis (I need to chagne its IP address) and I can't click on the "Save" button - it's grayed out.
Under hostname section, it says "Enter a valid URL", altough the URL is correct. 

![IMG_1797](https://user-images.githubusercontent.com/37050901/134173801-1958713d-6a7d-4e2f-8ac5-3069a39e1d94.PNG)

I tried to delete the app and reinstalled, didn't help.

**Comment by gdombiak** [comment]
Hmm, I wonder why it says that URL is not valid. Does it have an empty space at the end? I will try it locally and see if I can reproduce it

**Comment by gdombiak** [comment]
ok. I was able to reproduce it by doing the following:
1. Enter an invalid URL
2. Click on Scan and select an octoprint instance
3. Even though URL is completed .... message of invalid URL remains

If you tap on the URL and then tap on the printer name or API key or any other field it will remove the invalid URL message and will enable the button. I will fix this for the next release.

Thanks for reporting this issue.
Gaston

**Comment by 3DStyle** [comment]
Hello,
Did this issue got fixed? I’m still having this bug on v3.23 (build 1).

**Comment by the-one-carbon-fox** [comment]
i am haveing a similar issue. 
i am running the latest version i can on ipasos 12.2, I have also been trying to use octoeverwhere but it opens the page to add it then then i complete it it requests to open the page again. and if i try to do it it loops if i press cancel it exits the area. but i can see the text and stuff saying that it would work. but i cant press save

![Image](https://github.com/user-attachments/assets/081caeb9-1676-44be-9b6b-b7c1513571da)

and it loops. unless it is stoped then it cancels.
