### ISSUE TITLE
No longer connects to printer after iOS 15 update

### ISSUE THREAD

**Issue by MeganOhalloran** [gdombiak/OctoPod#518]
As soon as I downloaded the new iOS, octopod stopped connecting to my 3b+

**Comment by MeganOhalloran** [comment]
I get a message saying “Connection Failed. Service is down or incorrect port”

**Comment by gdombiak** [comment]
Interesting. I just started to download iOS 15 and will test once upgrade is completed. In the meantime, basic troubleshooting ideas:
* Restart iPhone and see if that still happens
* In iOS, go to Settings -> OctoPod and make sure that **Local Network** is enabled

Let me know if any of those 2 ideas worked.
Gaston

**Comment by MeganOhalloran** [comment]
Woah! Restarting worked! Local network was already enabled

**Comment by gdombiak** [comment]
That's great to hear that it's now working! Restarting phone has its magic. :)
