### ISSUE TITLE
Tasmota-MQTT plugs not visible

### ISSUE THREAD

**Issue by FrankX0** [gdombiak/OctoPod#520]
OctoPod is not showing my Tasmota plug.
Details:

- OctoPod: v3.13 build 1
- iOS: 15.0
- OctoPrint: 1.6.1
- OctoPod Plugin: 0.3.10 
- Tasmota-MQTT: 0.3.8

**Comment by gdombiak** [comment]
Hi @FrankX0,

Have you installed [Tasmota plugin](https://plugins.octoprint.org/plugins/tasmota/)? 

Gaston

**Comment by FrankX0** [comment]
Hi Gaston,

I have Tasmota-MQTT plugin installed.
Do I need Tasmota plugin instead/additionally?

Thanks,
Frank.

**Comment by gdombiak** [comment]
Hey @FrankX0 ,

Tasmota-MQTT is another plugin (that is not supported by OctoPod). If you need that plugin then try adding Tasmota plugin next to it so you can control switches from OctoPod. I think that you should be able to have both installed at the same time.

Let me know how it goes.

Gaston

**Comment by FrankX0** [comment]
Hi Gaston,

Yes, it's working with Tasmota directly.
I would have preferred through MQTT, but in this way it also works.
Thanks for the support.
