### ISSUE TITLE
Cant print with app with New octoprint 1.7.0

### ISSUE THREAD

**Issue by jrag1976** [gdombiak/OctoPod#526]
When I want to print with the app on the new version of octoprint 1.70 I can't do it because the app sends a warning that says: Warning Falied to request to print file.

The app works fine with octoprint 1.6.1.
The app fails to print with version 1.7.0.

**Comment by gdombiak** [comment]
Hi @jrag1976 , so far I'm not able to reproduce this error. Have some questions for you:
1. Does the error happen right after clicking Print from the Files window?
2. Does this happen with any file you try to print or with only one specific file? If only with 1 file could you share with me this file so I can reproduce this?
3. Do you have  Settings -> Privacy -> Analytics & Improvements -> Share With App Developers enabled? If not, could you enable it so I can get crash reports?

Thanks,
Gaston

**Comment by jrag1976** [comment]
1)It fails immediately after I click to print the file.

2)It fails with any file but I can send you one so you can try it.

3)I just enabled the analytic feature so you can get the error message to help you find out what’s going on.

I will try it tomorrow

Jose Arechiga


Sent from my iPhone

On Oct 12, 2021, at 8:15 PM, Gaston Dombiak ***@***.***> wrote:

﻿

Hi @jrag1976<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjrag1976&data=04%7C01%7C%7C361e75307bc74e99fee808d98df7a561%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637696917031202140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cNhtIn2UZgpNer%2Bia8RactGuv7sDbV22AI7wpl7X5x4%3D&reserved=0> , so far I'm not able to reproduce this error. Have some questions for you:

  1.  Does the error happen right after clicking Print from the Files window?
  2.  Does this happen with any file you try to print or with only one specific file? If only with 1 file could you share with me this file so I can reproduce this?
  3.  Do you have Settings -> Privacy -> Analytics & Improvements -> Share With App Developers enabled? If not, could you enable it so I can get crash reports?

Thanks,
Gaston

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgdombiak%2FOctoPod%2Fissues%2F526%23issuecomment-941877215&data=04%7C01%7C%7C361e75307bc74e99fee808d98df7a561%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637696917031212133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gA2BTmuLG1TuBMVhfh%2FD%2BfgO6w3yEp62c5z2FlzNbok%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATN2JUCHU3SHGIQ4MYI6J6LUGT2TLANCNFSM5F3QFK3A&data=04%7C01%7C%7C361e75307bc74e99fee808d98df7a561%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637696917031212133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BMBWNseNT2p%2FWPwDDRvsw26h01lu4uMsXUq7eUjCUzg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C361e75307bc74e99fee808d98df7a561%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637696917031222127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gzXzl4pu7dfCmFF%2BzqZqpaxMoBvpmCS31k3mvPDId8w%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C361e75307bc74e99fee808d98df7a561%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637696917031222127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YpXi1Qoq35x95BnXwkA2RALgy9kCpnEzqSTM5ttRZjA%3D&reserved=0>.

**Comment by jrag1976** [comment]
Estas son las foto.

[cid:DC8BF1FC-CE47-48D7-A2E5-6F7E4C35C47D-L0-001][cid:436F2771-7395-404B-B841-68AED2DC2F41-L0-001]

Sent from my iPhone

On Oct 13, 2021, at 10:22 AM, Gaston Dombiak ***@***.***> wrote:

﻿

Hola Jose,

Gracias por la info. La foto no aparece acá. Si quieres me la podes mandar a mi cuenta de gmail (gdombiak en gmail). Me podrías mandar una copia de los nombres de los archivos que estas imprimiendo? Quiero ver si hay algún carácter que pueda causar el problema.

Otras preguntas:

  1.  que localidad estas usando en OctoPi? Cambiaste el valor por defecto?
  2.  La impression comienza cuando pedis Print o el crash ocurre antes.

Por ahora no encuentro el crash reportado por tu app. Sigo mirando.

Gracias,
Gaston

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgdombiak%2FOctoPod%2Fissues%2F526%23issuecomment-942545778&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532481653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TfHKjHG25roampSheq%2BdxNG2kETW3lbt8EGxgEn0ZhA%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATN2JUEJIZE5URXWR22Q7M3UGW55PANCNFSM5F3QFK3A&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532491646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MDBNgnYkEKvIiulFY1YNAr8e3NOIn3WGt%2FOH27xb4uc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532491646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k%2Bvh2nB1%2BJjZfTkFftjh3NE9kxdwZngmhlAj2wTY5B0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532501643%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1D8ts6vqjL%2BbaxA2wy7v60BkZJMh5hTAfWujFqdXAp0%3D&reserved=0>.

**Comment by jrag1976** [comment]
1) La localidad de octopi es la que esta por defecto.
2)El crash ocurre cuando seleccion que se imprima el archivo. Al presionar “yes print file”  y no imprime nada solo me muestra las fotos del correo anterior.

Lo que si acabo ahorita es que al imprimir por me dio remoto(vpn) me marca otro error.



[cid:A4C7B3B2-297E-4942-B459-3DEC9C81626F-L0-001]

Pero si desconecto la impresora y me vuelvo a conectar y pongo a imprimir un archivo que se llama SLOTS.gcode si lo manda a imprimir pero si lo canelo y lo quiero imprimir otra vez me falla y me marca el error de la foto pasada.

Para hacerlo que imprima tengo que desconectar la impresora del app y volverla a conectar, luego seleccion el archivo a imprimir y si lo hace.

Voy a intentar esto con los otros archivos y te aviso si también los imprime.

Te aviso


Sent from my iPhone

On Oct 13, 2021, at 10:22 AM, Gaston Dombiak ***@***.***> wrote:

﻿

Hola Jose,

Gracias por la info. La foto no aparece acá. Si quieres me la podes mandar a mi cuenta de gmail (gdombiak en gmail). Me podrías mandar una copia de los nombres de los archivos que estas imprimiendo? Quiero ver si hay algún carácter que pueda causar el problema.

Otras preguntas:

  1.  que localidad estas usando en OctoPi? Cambiaste el valor por defecto?
  2.  La impression comienza cuando pedis Print o el crash ocurre antes.

Por ahora no encuentro el crash reportado por tu app. Sigo mirando.

Gracias,
Gaston

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgdombiak%2FOctoPod%2Fissues%2F526%23issuecomment-942545778&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532481653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TfHKjHG25roampSheq%2BdxNG2kETW3lbt8EGxgEn0ZhA%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATN2JUEJIZE5URXWR22Q7M3UGW55PANCNFSM5F3QFK3A&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532491646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MDBNgnYkEKvIiulFY1YNAr8e3NOIn3WGt%2FOH27xb4uc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532491646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k%2Bvh2nB1%2BJjZfTkFftjh3NE9kxdwZngmhlAj2wTY5B0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532501643%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1D8ts6vqjL%2BbaxA2wy7v60BkZJMh5hTAfWujFqdXAp0%3D&reserved=0>.

**Comment by jrag1976** [comment]
Otra pregunta tu app no trabaja con Android ¿Algún día piensas hacer el app para android?



Sent from my iPhone

On Oct 13, 2021, at 3:54 PM, J. Rogelio Aréchiga ***@***.***> wrote:

﻿ 1) La localidad de octopi es la que esta por defecto.
2)El crash ocurre cuando seleccion que se imprima el archivo. Al presionar “yes print file”  y no imprime nada solo me muestra las fotos del correo anterior.

Lo que si acabo ahorita es que al imprimir por me dio remoto(vpn) me marca otro error.



[cid:A4C7B3B2-297E-4942-B459-3DEC9C81626F-L0-001]

Pero si desconecto la impresora y me vuelvo a conectar y pongo a imprimir un archivo que se llama SLOTS.gcode si lo manda a imprimir pero si lo canelo y lo quiero imprimir otra vez me falla y me marca el error de la foto pasada.

Para hacerlo que imprima tengo que desconectar la impresora del app y volverla a conectar, luego seleccion el archivo a imprimir y si lo hace.

Voy a intentar esto con los otros archivos y te aviso si también los imprime.

Te aviso


Sent from my iPhone

On Oct 13, 2021, at 10:22 AM, Gaston Dombiak ***@***.***> wrote:

﻿

Hola Jose,

Gracias por la info. La foto no aparece acá. Si quieres me la podes mandar a mi cuenta de gmail (gdombiak en gmail). Me podrías mandar una copia de los nombres de los archivos que estas imprimiendo? Quiero ver si hay algún carácter que pueda causar el problema.

Otras preguntas:

  1.  que localidad estas usando en OctoPi? Cambiaste el valor por defecto?
  2.  La impression comienza cuando pedis Print o el crash ocurre antes.

Por ahora no encuentro el crash reportado por tu app. Sigo mirando.

Gracias,
Gaston

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgdombiak%2FOctoPod%2Fissues%2F526%23issuecomment-942545778&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532481653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TfHKjHG25roampSheq%2BdxNG2kETW3lbt8EGxgEn0ZhA%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATN2JUEJIZE5URXWR22Q7M3UGW55PANCNFSM5F3QFK3A&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532491646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MDBNgnYkEKvIiulFY1YNAr8e3NOIn3WGt%2FOH27xb4uc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532491646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k%2Bvh2nB1%2BJjZfTkFftjh3NE9kxdwZngmhlAj2wTY5B0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9ec0458f01fb4769e6c008d98e6e0a4e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637697425532501643%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1D8ts6vqjL%2BbaxA2wy7v60BkZJMh5hTAfWujFqdXAp0%3D&reserved=0>.
