### ISSUE TITLE
Executing system commands results in error

### ISSUE THREAD

**Issue by TheLion** [gdombiak/OctoPod#532]
Hi,

When executing certain, not all, system command (see screenshot) results in an error. For example setting the exposure.

![2021-10-16 20-19-15](https://user-images.githubusercontent.com/3755011/137598223-ac0346dc-95fa-45b5-80c1-70b47d40fdc9.png)

Through the web interface directly in Octoprint they work fine. The system command for stopping and starting the video stream works just fine, strangely enough.

It is the same on both my (physical separate) Octoprint instances.

This is with the latest OctoPod v3.14 build 3, the previous had the same issue, not sure with earlier releases.

**Comment by gdombiak** [comment]
Hi @TheLion,

I think the problem is the % that appears at the end of the **action**. You can keep the % in the name but try removing it from the action and let me know if that worked. For some reason OctoPrint is encoding the % differently than expected.

Thanks,
Gaston

**Comment by TheLion** [comment]
> I think the problem is the % that appears at the end of the **action**. You can keep the % in the name but try removing it from the action and let me know if that worked. For some reason OctoPrint is encoding the % differently than expected.


I will try that and let you know, but it has always worked like this. Also  through Octopod.

**Comment by gdombiak** [comment]
Thanks Martijn! That last piece of information helped me fixed it (i.e. that used to work before). I fixed it and also found same problem downloading or deleting timelapse files. 

Gaston

**Comment by gdombiak** [comment]
New version is out. Please upgrade and let me know how it goes. 

Thanks 
Gaston

**Comment by TheLion** [comment]
> New version is out. Please upgrade and let me know how it goes.

Just got a notification from TestFlight ;-)
It works like a charm! Thanks!
