### ISSUE TITLE
TPLink plugs not appearing at all in app

### ISSUE THREAD

**Issue by joshuacant** [gdombiak/OctoPod#538]
Hi, I have the following set up:

Octopi 0.18.0
Octoprint 1.7.0
OctoPod Plugin 0.3.11
TP Link Plugin 1.0.1
OctoPod iOS App 3.15

Everything works as you would expect it to. I can control the TPLink plug via the Octoprint WebUI, I can access OctoPrint via OctoPod and view/control my printer. However, the app does not display the TPLink plugs for me to control. They just aren't there. I've seen screenshots from others, including some posted to this github, and the panel where they should be is completely missing.

Is this a configuration error on my end, or was the feature for controlling TPLink plugs removed at some point? Most of the posts I see about it are 2-3 years old now, so that seems like a possibility. 

Thanks for your time, and all your hard work on this app.

**Comment by joshuacant** [comment]
Hi, thanks for the reply. I've attached a screenshot I just took of Octopod on my iPhone.
![capture](https://user-images.githubusercontent.com/1975723/138618113-dc0cd145-c97c-4de0-bdf3-b2ed4b719824.jpg)

I only have 4 panels to swipe through. I don't have the other plugins shown in the video however, so I guess that's no great surprise. But I do have the TPLinkSmartplug one:

![capture2](https://user-images.githubusercontent.com/1975723/138618272-3b1f3b71-0005-4335-90f2-1eda49104001.png)

So I think if I understand your second question, it's not that the page showing plugs is empty, it's not there at all.

**Comment by gdombiak** [comment]
Hi Joshua,

I think I see what is going on. The plug seems to not have a name. This is how I set it up in my local environment.

![Screen Shot 2021-10-24 at 5 13 31 PM](https://user-images.githubusercontent.com/1791267/138618512-2e42b87c-0cfc-488b-9cc2-164b2c985db0.png)

![Screen Shot 2021-10-24 at 5 17 21 PM](https://user-images.githubusercontent.com/1791267/138618571-ec207b96-487b-4659-9580-3bb2a7321d39.png)

Once a name has been entered, plugs will appear in OctoPod as shown in the demo. Let me know if this is not working for you.

Thanks,
Gaston

**Comment by gdombiak** [comment]
BTW, remember to swipe to the right (or left) the bottom panel so you can access more functionality in OctoPod like temp charts, RPi temp chart, system commands and any other plugin that you have installed like TPLink.

Gaston

**Comment by joshuacant** [comment]
Yep, that fixed it. I left that blank because the TPLink plugin describes it thusly: 

![image](https://user-images.githubusercontent.com/1975723/138618961-2698fe34-61ef-43e1-8447-a1e9bb6ac5a2.png)

and I didn't think a name only visible in a tool top was necessary. That said, now that I have entered it, I see that the TP Link plugin itself uses it as the plug's name. I know I'm barking up the wrong tree here, but I think that input should be changed from Label to Name and made a required field. 

Thank you for your help. In the end it did end up being a mis-configuration on my part, so I apologize for taking up your time with it.
