### ISSUE TITLE
Unable to login to OctoEverywhere via Google

### ISSUE THREAD

**Issue by jdtaormi** [gdombiak/OctoPod#545]
iPhone 12 Pro 
iOS 15.1.1

Adding an OctoEverywhere printer and trying to login via Google results in

"Error 403: disallowed_useragent"

https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#authorization-errors-disallowed-useragent

**Comment by jbreu** [comment]
Yup, same for me. Can’t login and use the app because of that

**Comment by gdombiak** [comment]
Hey guys,

IIRC, there is a workaround to this problem that was shared by OctoEverywhere developer. I will take a look at this error again but so far I was not able to figure out how to fix it. In the meantime, use the workaround (sorry I do not remember it - maybe it was just using regular login with your email but not sure which password - OctoEverywhere developer can help with this).

Regards,
Gaston

**Comment by jdtaormi** [comment]
I believe I was able to get around it by doing a password reset for my
email which allowed me to login directly to the site
