### ISSUE TITLE
Add Cancel/Reset/Resume buttons.

### ISSUE THREAD

**Issue by nerkaid** [gdombiak/OctoPod#56]
With that buttons, this app would be the best in iOS for control Octoprint. Thanks for this great job!

**Comment by gdombiak** [comment]
Hola nerkaid,

When you are printing, there is an (i) icon next to "Printed" where you see the progress bar. If you click on the (i) you will get a window that lets you pause, resume, restart or cancel the print.

Is that what you were looking for?

Gracias
Gaston (de Argentina) ;)

**Comment by nerkaid** [comment]
Exactly that! Sorry I didn't realize it. You can close the ticket. 

Gracias por tu gran trabajo, la aplicación es un pasada!! 

Saludos desde España ;)

**Comment by gdombiak** [comment]
Estoy creando un archivo con los nombres de las personas que ayudaron crecer a OctoPod. Si me das tu nombre te agrego, sino uso tu alias que veo aca. :)

**Comment by nerkaid** [comment]
Hola,

 

Luis F. Fernández, o nerkaid, como prefieras!

Gracias! 😉

 

Un saludo,

Luis F. Fernández

 

De: Gaston Dombiak <notifications@github.com> 
Enviado el: sábado, 8 de septiembre de 2018 19:39
Para: gdombiak/OctoPod <OctoPod@noreply.github.com>
CC: nerkaid <nk@nerkaid.com>; Author <author@noreply.github.com>
Asunto: Re: [gdombiak/OctoPod] Add Cancel/Reset/Resume buttons. (#56)

 

Estoy creando un archivo con los nombres de las personas que ayudaron crecer a OctoPod. Si me das tu nombre te agrego, sino uso tu alias que veo aca. :)
