### ISSUE TITLE
Missing pause/cancel print buttons

### ISSUE THREAD

**Issue by vordenken** [gdombiak/OctoPod#562]
The buttons are missing in the app but after force closing and reopening it the buttons appear. 
Here are two screenshots showing the problem: 

1. Buttons missing
![image](https://user-images.githubusercontent.com/62395860/152695793-537f9677-fea9-422c-b5f7-47ae7a28cef2.png)

2. Buttons showing up
![image](https://user-images.githubusercontent.com/62395860/152695817-a2f86674-3e8a-46f8-ae6a-e0ce6c56c05c.png)

Latest OctoPi, OctoPrint and OctoPod (App and Plug-in) 

If you need more informations let me know :)

**Comment by gdombiak** [comment]
Hi @vordenken,

Thanks for reporting this bug. I never saw it before. Buttons should always appear when file name being printed appears. Is there a way you can provide information on how to reproduce this error? When did it start to happen? Does it happen with any file being printed? Any info would help know how to reproduce this.

Danke!
Gaston

**Comment by vordenken** [comment]
Hi @gdombiak,

I think the problem only occurs if the print is already going and I open the app afterwards. If the app is open while starting the print, it shows the buttons correctly. 

It also happens with any file, tested a few yesterday. If there are any logs I can provide, let me know where to find them :) 

Gern 👍🏼

**Comment by gdombiak** [comment]
Gern, I spent more time trying to reproduce this and so far no luck. Let me know if you find more info on how to reproduce this. I will ask in the Facebook group to see if anyone else is having this issue so I can figure out how to reproduce it ... and then fix it.

Danke
Gaston

**Comment by PalatinCoder** [comment]
Hi @gdombiak ,
Just want to let you know that I noticed this problem as well. As @vordenken did, I too started the print via OctoPrint‘s web interface and opened the OctoPod App afterwards. Force-closing and reopening brought the buttons back. I‘ll see if I can reproduce it reliably

**Comment by jimwhitelaw** [comment]
I’m able to reproduce this reliably by scrolling the bottom print info section upward until the pause/cancel buttons are hidden. When scrolling back down the buttons (text) are missing. 

On iPad, if I leave the app and return to it, they reappear. On iPhone, I can only get them back if I kill the app and restart. 

iPad Pro 11” iOS 15.3.1 
IPhone XR iOS 15.3.1

**Comment by gdombiak** [comment]
Hi @jimwhitelaw,

This is great. Thanks for sharing this extra info on how to reproduce this. I will give it a try and hope to be able to reproduce this so I can fix it.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Thanks @jimwhitelaw . With your information I was able to reproduce this issue in no time. So weird that I never came across this bug. I will try to make room this week and fix this issue and push a new release.

Thanks again,
Gaston

**Comment by jimwhitelaw** [comment]
Fantastic. I'm glad the info was helpful. The app is great and I'm very happy with it. thx.

**Comment by gdombiak** [comment]
New release is out. Let me know if you still see this issue.

Thanks,
Gaston
