### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by Nawyer** [gdombiak/OctoPod#571]
Hey man! Love your work and more than happy to throw some cash your way to help you continue developing.
Not really an issue just wanted to know how to best contact you (I'm a noob with github). 
Also, could you possibly add me to the app list of sponsors? That's such a rad idea by the way.
Thanks!
N8

**Comment by gdombiak** [comment]
Hi @Nawyer!

First off, thanks SO MUCH for being a sponsor of OctoPod. :) You can contact post ideas, bugs or requests here in Github by creating new issues. You can also contact me directly via email to gdombiak at gmail if you prefer. I will work this weekend on updating the list of sponsors! You certainly deserve to be there! I will see of making the list dynamic so I do not have to do a new release of OctoPod to update the list.

Thanks again,
Gaston
