### ISSUE TITLE
Sharing Timelapse causes Octopod to crash

### ISSUE THREAD

**Issue by andyylin** [gdombiak/OctoPod#580]
1. Go to Files > Timelapse
2. Swipe left on a Timelapse
3. Press on Share button
4. Timelapse starts downloading
5. At 100%, OctoPod crashes to the Home Screen

**Comment by gdombiak** [comment]
Hi @andyylin,

Thanks for detailed bug report. This will help a lot in reproducing and fixing this. BTW, do you have "Share with App Developers" enabled under Settings -> Privacy -> Analytics & Improvements? By enabling that, app developers receive more detail about app crashes that help fix things.

Thanks again,
Gaston

**Comment by andyylin** [comment]
> Hi @andyylin,
> 
> 
> 
> Thanks for detailed bug report. This will help a lot in reproducing and fixing this. BTW, do you have "Share with App Developers" enabled under Settings -> Privacy -> Analytics & Improvements? By enabling that, app developers receive more detail about app crashes that help fix things.
> 
> 
> 
> Thanks again,
> 
> Gaston

No, I did not enable that. I've enabled it now. Thanks for letting me know!

**Comment by andyylin** [comment]
After some more testing, I've found it crashes the iPad app but not the iPhone app.

**Comment by gdombiak** [comment]
That is very interesting and good info so I can reproduce it. Thanks for enabling those logs so I can gather more info. Will update this thread as I found more info or have a fix.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Exactly as you reported. It crashed on my ipad but works on my iphone. Will try fixing it this weekend and push a new release.

Thanks,
Gaston
