### ISSUE TITLE
Landscape view does not show camera feed on iPad Mini 6

### ISSUE THREAD

**Issue by ShodaPublicity** [gdombiak/OctoPod#583]
The camera feed shows in portrait mode, but when you flip the device to landscape mode then the camera feed disappears. This seems similar to the following issue: https://github.com/gdombiak/OctoPod/issues/414

OS: iOS/iPadOS 15.4.1
Devices: iPhone 12 Pro and iPad Mini 6

Reproduction Steps:
1. Go to Panel Tab
2. Place device in portrait mode (camera feed is visible)
3. Turn device to landscape mode (camera feed disappears while the print job status is scrolled upstairs and pushes camera feed out of window)
4. Turn device back to portrait mode (camera feed reappears)

**Comment by gdombiak** [comment]
Hi @ShodaPublicity,

Thanks for reporting this. The behavior you described is expected on the iPhone due to a small screen when in landscape. However, this is not ok for the iPad Mini that has a way bigger screen. I will add support for the iPad Mini for the next release.

Thanks,
Gaston
