### ISSUE TITLE
Spaghetti Detective doesn’t work with name change to Obcio

### ISSUE THREAD

**Issue by ant2002k** [gdombiak/OctoPod#587]
Spaghetti detective changed their name to Obcio. Unfortunately you can’t add a (formerly) TSD printer now because there’s some kind of mismatch with the website.

**Comment by gdombiak** [comment]
Thanks so much for letting me know about this issue. Fixing it for the next release that should be out in a couple of days.

**Comment by gdombiak** [comment]
Good news! I contacted the Spaghetti Detective developer and they fixed an issue on their side that was not letting you add new printers. I just tested it and it is working fine now. The only change I will do in a future release is about the name and logo.

Thanks,
Gaston
