### ISSUE TITLE
Not able to install from the Slovak region App store

### ISSUE THREAD

**Issue by frizzy** [gdombiak/OctoPod#596]
Hi,

Is it possible to make this app available in the Slovakia region. I cannot switch to another region's app store to download this.

Thanks

**Comment by gdombiak** [comment]
HI @frizzy,

I have not put any restrictions of where the app should be available. I expected for it to be available anywhere in the world. Let me read more about this and see if I discover anything that I could do to solve this.

Thanks for letting me know,
Gaston

**Comment by gdombiak** [comment]
Yep, looking at the App Store configuration I see that it should be available everywhere in the world including Slovakia. I wonder if this is transitory issue in the App Store?

<img width="687" alt="Screen Shot 2022-07-24 at 9 25 51 AM" src="https://user-images.githubusercontent.com/1791267/180656778-3d9b9509-686b-4983-907e-d54fa560039f.png">

**Comment by frizzy** [comment]
Hi @gdombiak .Thanks for your help! .. I managed to install it now. It appears to have been something with my iPad/Account. I'm able to install the app now. Sorry about the false alarm.
