### ISSUE TITLE
Feature Request: gcode-Upload from another application via Share

### ISSUE THREAD

**Issue by p3d-dev** [gdombiak/OctoPod#597]
Great application. Many thanks for providing this.

There is already a slicer application for iPad. This means the gcode files can be directly created on the ipad. Now it would be great, if the resulting gcode files could be shared or drag-and-dropped from the slicer to Octopod for upload to Octoprint. This would be more convenient than via storing files somewhere in the iPad file system from within the slicer, then open Octopod, go to the file manager. navigate in the file system to the gcode file and then upload it.

Any chance to have this supported ?

**Comment by gdombiak** [comment]
Hi @p3d-dev,

I wonder if this existing OctoPod feature can do what you are looking for. Open OctoPod and go to the Files window. There you can click "Upload to OctoPrint (or SD Card)" at the top right. If generated files from the slicer application can be uploaded to iCloud Drive or left in your phone as files then you will be able to select them and upload them to OctoPrint to be able to print as usual.

Hope this helps,
Gaston

**Comment by gdombiak** [comment]
Absolutely!!!! What kind of integration do you have in mind between both apps?

Gastpm
