### ISSUE TITLE
Time to finish printing and name of model not showing up after Octoprint update 

### ISSUE THREAD

**Issue by Printyprinty** [gdombiak/OctoPod#605]
Please help. Title and time to finish not displaying after new octoprint uodate

**Comment by theHalo** [comment]
Same problem here. 
All print job information is missing. 
Temperature settings are shown but temperature  history graph says no history available. 

![18B139CC-6B79-4330-BF7A-3F8A76935E0B](https://user-images.githubusercontent.com/26176515/191501733-5838cae0-9081-419c-a6bf-c9334372386e.png)

**Comment by gdombiak** [comment]
Thanks for reporting this. I will take a look during the weekend.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Got to the bottom of this,. OctoPrint 1.8.3 hits an error when using global API keys as reported [here](https://github.com/OctoPrint/OctoPrint/issues/4648). I changed the API key to use an Application Key and things work well now. If it's easier, you can remove the printer and add it again to OctoPod. Make sure to select "OctoPrint - Application Key" when adding the printer again.

Let me know how it goes.

Gaston

**Comment by theHalo** [comment]
Replacing the API key with a new application key worked like a charm. 
Thanks!
