### ISSUE TITLE
Print - Pause - Cancel missing

### ISSUE THREAD

**Issue by mollywaters** [gdombiak/OctoPod#606]
The ability to pause and resume or cancel a print is no longer available. These options were on the panel screen and they are now missing after a recent update.

**Comment by Printyprinty** [comment]
Yeah having same problem. Hopefully the developer addresses these issues soon. Pretty annoying to have to run back to my laptop to control prints. Defeats the whole purpose of the app.

**Comment by gdombiak** [comment]
Hey guys,

Sorry this is happening. Which version of OctoPrint are you running? Did this happen after you updated OctoPrint?

Thanks,
Gaston

**Comment by Printyprinty** [comment]
The most recent update of 1.8.3. It have it on two of my machines and they don’t display the name, time left, cancel, or pause buttons. On the two that I didn’t upgrade, Octopod works just fine.

**Comment by mollywaters** [comment]
I also have two machines also using the most recent version of Octoprint 1.8.3 both with the same issue. Sent from my iPhoneOn Sep 22, 2022, at 2:13 PM, Printyprinty ***@***.***> wrote:﻿
The most recent update of 1.8.3. It have it on two of my machines and they don’t display the name, time left, cancel, or pause buttons. On the two that I didn’t upgrade, Octopod works just fine.

**Comment by gdombiak** [comment]
Got to the bottom of this,. OctoPrint 1.8.3 hits an error when using global API keys as reported [here](https://github.com/OctoPrint/OctoPrint/issues/4648). I changed the API key to use an Application Key and things work well now. If it's easier, you can remove the printer and add it again to OctoPod. Make sure to select "OctoPrint - Application Key" when adding the printer again.

Let me know how it goes.

Gaston

**Comment by mollywaters** [comment]
That worked. Thanks. Sent from my iPhoneOn Sep 25, 2022, at 12:59 AM, Gaston Dombiak ***@***.***> wrote:﻿
Got to the bottom of this,. OctoPrint 1.8.3 hits an error when using global API keys as reported here. I changed the API key to use an Application Key and things work well now. If it's easier, you can remove the printer and add it again to OctoPod. Make sure to select "OctoPrint - Application Key" when adding the printer again.
Let me know how it goes.
Gaston
