### ISSUE TITLE
Needs updating for OctoPrint 1.8.3

### ISSUE THREAD

**Issue by megatech1966** [gdombiak/OctoPod#607]
Needs updating for OctoPrint 1.8.3
No eta percentage etc info displayed

**Comment by gdombiak** [comment]
Thanks for reporting this. I see many issues being reported after updating OctoPrint. Will take a look this weekend. Hope to have a new release soon after.

Regards,
Gaston

**Comment by gdombiak** [comment]
Got to the bottom of this,. OctoPrint 1.8.3 hits an error when using global API keys as reported [here](https://github.com/OctoPrint/OctoPrint/issues/4648). I changed the API key to use an Application Key and things work well now. If it's easier, you can remove the printer and add it again to OctoPod. Make sure to select "OctoPrint - Application Key" when adding the printer again.

Let me know how it goes.

Gaston
