### ISSUE TITLE
Feature Request: IOS 16 Widgets

### ISSUE THREAD

**Issue by samuellogan** [gdombiak/OctoPod#608]
It would be amazing if this app added support for the new lock screen widgets on IOS 16. This would allow users to see their print progress at a glance, just like what is implemented for apple watch.

**Comment by gdombiak** [comment]
Thanks @samuellogan for this request. I will try adding support for this in the 3.25 release. I'm now pushing out 3.24 as an "urgent" release.

**Comment by F3000** [comment]
can you consider also live activities? 

@gdombiak

**Comment by gdombiak** [comment]
Live Activities are now implemented. Starting final round of testing before calling it done. I will keep this ticket opened for just the new widgets that can be added in the lock screen /focus window.

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-12 at 15 39 36](https://user-images.githubusercontent.com/1791267/224580713-ae0a0296-688b-420c-b146-5bac6332ec6b.png)
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-12 at 15 39 47](https://user-images.githubusercontent.com/1791267/224580721-14f99c78-aafe-495e-899e-28f4cc2deccb.png)
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-12 at 15 39 51](https://user-images.githubusercontent.com/1791267/224580725-369a9738-4caa-498f-bd65-1394bd3f3040.png)

**Comment by gdombiak** [comment]
Added Lock Screen Widgets right on time before the next release!!!

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-18 at 21 25 27](https://user-images.githubusercontent.com/1791267/226153947-e5c4e13a-e1a1-48e9-b047-a476cd387908.png)
