### ISSUE TITLE
Live activities iOS

### ISSUE THREAD

**Issue by Morcegolas** [gdombiak/OctoPod#625]
Hello, is there any chance to add this wonderful app to the live activities, it would be awesome.

**Comment by josephsamela** [comment]
I second this request! Adding a live activity notification would be super helpful. Here's a concept of what an Octoprint live activity notification might look like. The idea here is that during a print the live activity notification would appear showing live information such as... 
- Printer name
- File name
- Tool temperature
- Bed temperature
- Percent complete
- Est. time remaining
- Webcam preview

<img src="https://user-images.githubusercontent.com/16111451/215227848-1149498c-48bb-428a-98d2-535282f4d326.jpg" width="400" height="400">

**Comment by gdombiak** [comment]
dup of https://github.com/gdombiak/OctoPod/issues/635
