### ISSUE TITLE
Light Background In Live activity iOS

### ISSUE THREAD

**Issue by pratik1989** [gdombiak/OctoPod#641]
![IMG_6083](https://user-images.githubusercontent.com/48381753/230350442-1e85ef2f-e922-4135-bf8d-db9ccf759ef3.jpeg)

The live activity for octopod is light in dark mode which doesn’t match with other notification backgrounds and doesn’t look good. Can it be matched to dark as with other notifications or live activity tiles?

**Comment by DominikPalo** [comment]
Agree, it looks strange
![IMG_2556](https://user-images.githubusercontent.com/1623257/232224659-7f6c9890-2ab9-4dfa-a803-5df02f4c6ae4.jpg)

**Comment by gdombiak** [comment]
Thanks @pratik1989 for reporting this. I solved it today as part of https://github.com/gdombiak/OctoPod/issues/663.

Regards,
Gaston
