### ISSUE TITLE
Widget color seems to be non-standard

### ISSUE THREAD

**Issue by Indemnity83** [gdombiak/OctoPod#663]
I'm not sure if this is a "bug" or intended behavior, but the lock screen widget color doesn't appear to adjust to the standard/default colors as the phone moves through modes. 

In light mode, with the screen unlocked the widget color looks ALMOST right, just slightly off and some may not notice. But if the phone is in dark mode, all other widgets get darker except OctoPod. Similarly, when the phone is locked with an always-on display the widget is STILL a relatively bright color. 

I'm guessing that the color is hard-coded somewhere when it doesn't need to be? 

I tried forking the repo and looking at the code myself, but I'm not an Ios Developer and got lost; if somebody can point me to the right place I'm glad to take a stab at a PR.

**Comment by gdombiak** [comment]
Hi Kyle,

Thanks for reporting this. You are correct in your assessment about having the [color hardcoded](https://github.com/gdombiak/OctoPod/blob/b9f0ae364398b41673c4894595d932a556eed5c7/OctoPodWidget14/LiveActivityWidget.swift#L147). Let me know if you want to give it a take at a PR or if you want me to take care of this. The correct fix would be to consider the OctoPod setting for appearance. If you want to follow the system setting then color should change when using dark mode. If someone wants to always be light or dark mode then the backgroundcolor wouldn't change.

FYI, I'm planning to push next release out this week. If we cannot make it on time then I will include it in the next one.

Thanks,
Gaston
