### ISSUE TITLE
Negative value in filament manager causes crashes

### ISSUE THREAD

**Issue by eeker79** [gdombiak/OctoPod#678]
I have created an “untracked” spool in filament manager to select in case of old, non-standard, etc filament.
Total weight left on that spool is already in negative value.
When that spool is selected, Octopod immediately crashes when I am in filament manager panel.

**Comment by gdombiak** [comment]
Thanks @eeker79 for reporting this. I will let you know if I need more info reproducing this crash.

Gaston
