### ISSUE TITLE
IOS app won't sync to iCloud - "failed to update some records"

### ISSUE THREAD

**Issue by Grumps1969** [gdombiak/OctoPod#683]
I have the OctoPod app running on my iPhone 14, but it won't sync printer info to the cloud.
Error message from app's log is:
"_Failed to push changes for printer: http://**[IP on local network]**. Error: Failed to modify some records._"

When I try to run OctoPod on my AppleTV it just shows "retrieving printer info..." and never completes.

I've removed & reinstalled the app on my phone, but it didn't help.
Any idea what setting(s) I might be missing?

Thank you

**Comment by janfryauf** [comment]
Exactly the same happening to me. I also tried ‘Reset iCloud data from printers’ and still getting the same error. Apple TV won’t load anything. Any fix?

**Comment by 3DStyle** [comment]
Same here. My printers will not sync between devices. What's going on?

**Comment by Grumps1969** [comment]
Sadly I've given up - never got it working, and at the same time managed to break my printer (damage unrelated to Octoprint).
The new one I've ordered to replace it is not compatible with Octoprint, at least not yet?
Good luck to you all.  Maybe I'll be back some day.

**Comment by assumebreach** [comment]
Same issue here!!

**Comment by corpjester** [comment]
Same issue here. Can’t sync to iCloud, getting identical error as above.

**Comment by jatkins11** [comment]
Sadly I'm getting the same error as well. I did a little googling and found this post on [Stack Exchange](https://stackoverflow.com/questions/51254169/cloudkit-failed-to-modify-some-records-zone-not-found) where there may be an issue with the way the app is trying to access a zone, but I'm not an iOS app developer so I can't say for sure.

**Comment by camrichmond** [comment]
Yep, getting the same issue here as well. I was trying to change the name of my printer on my Apple TV and now I can't get it to sync from any iOS devices.

**Comment by billy27607** [comment]
Me too

**Comment by gdombiak** [comment]
Hi guys,

Sorry this is happening to all of you. Wonder if you can help me gather more information so I can troubleshoot this. Could you do the following and share the results:

1. Open OctoPod and go to "Settings"
2. Click on "Devices"
3. Click on "Reset printers from iCloud"
4. If this fails and click on "View activity log"
5. Paste screenshot or results here

Thanks,
Gaston

**Comment by billy27607** [comment]
Sent from my iPhoneOn Mar 4, 2024, at 12:30 AM, Gaston Dombiak ***@***.***> wrote:﻿
Hi guys,
Sorry this is happening to all of you. Wonder if you can help me gather more information so I can troubleshoot this. Could you do the following and share the results:

Open OctoPod and go to "Settings"
Click on "Devices"
Click on "Reset printers from iCloud"
If this fails and click on "View activity log"
Paste screenshot or results here

Thanks,
Gaston

**Comment by camrichmond** [comment]
Sure thing. The first two messages pop up when clicking, "Reset printers from iCloud data."
The last two are from clicking, "Reset iCloud data from printers."

![IMG_5449](https://github.com/gdombiak/OctoPod/assets/11050248/3e91cc9b-86b1-4626-b746-617843a94bf7)

**Comment by corpjester** [comment]
Same result as the others. Nothing happens, screenshot attached:

￼

**Comment by gdombiak** [comment]
Hey guys, I created a new version that will help me collect more data to see what’s going on with this error.  If you are already a beta tester go ahead and install the new version and follow the steps I mentioned above. Share a screenshot with the results. You might want to rotate the phone for the screenshot if the text is not fully visible. 

If you are not a beta tester then send me a message and I’ll add you to the list of testers. 

Thanks 
Gaston

**Comment by camrichmond** [comment]
> If you are not a beta tester then send me a message and I’ll add you to the list of testers.
I feel stupid for asking, but how do I message you? I'd like to help you out.

**Comment by billy27607** [comment]
You can reach me at ***@***.***  I would be happy to help test.  Sent from my iPhoneOn Mar 11, 2024, at 4:29 PM, camrichmond ***@***.***> wrote:﻿

If you are not a beta tester then send me a message and I’ll add you to the list of testers.
I feel stupid for asking, but how do I message you? I'd like to help you out.

**Comment by corpjester** [comment]
Please add me to the beta testers, I’d be glad to help out. Sent from my iPhoneOn Mar 11, 2024, at 4:01 PM, Gaston Dombiak ***@***.***> wrote:﻿
Hey guys, I created a new version that will help me collect more data to see what’s going on with this error.  If you are already a beta tester go ahead and install the new version and follow the steps I mentioned above. Share a screenshot with the results. You might want to rotate the phone for the screenshot if the text is not fully visible.
If you are not a beta tester then send me a message and I’ll add you to the list of testers.
Thanks
Gaston

**Comment by corpjester** [comment]
> Hey guys, I created a new version that will help me collect more data to see what’s going on with this error. If you are already a beta tester go ahead and install the new version and follow the steps I mentioned above. Share a screenshot with the results. You might want to rotate the phone for the screenshot if the text is not fully visible.
> 
> If you are not a beta tester then send me a message and I’ll add you to the list of testers.
> 
> Thanks Gaston

Hi, please add me to the beta list for the version to troubleshoot Octopod. 
Thanks in advance! Hope to hear from you soon.

**Comment by gdombiak** [comment]
Good question about sending me a message. :) You can send me an email to gdombiak at gmail.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Good news! Thanks Michael Goran for sharing your screenshots and providing vital information. Everyone, give it a try and let me know if things are now resolved.

Thanks,
Gaston

**Comment by billy27607** [comment]
I can report that all is working.

**Comment by gdombiak** [comment]
Good! I got confirmation from 2 people that this issue is now resolve. Sorry for taking this long to resolve it. Too many other things are keeping me busy atm.
