### ISSUE TITLE
Camera status indicator

### ISSUE THREAD

**Issue by Nathan-Julian** [gdombiak/OctoPod#694]
It would be really nice if there was some sort of an indicator for when the camera view is live or not. Sometimes when you attempt to move the printer and it doesn't immediately appear to move it is just the camera not updating. Some sort of symbol in the corner to indicate that the camera is not live would be useful.

**Comment by gdombiak** [comment]
Hi @Nathan-Julian,

Such a great suggestion. I realized the other day that I needed to give a hint when camera is not actually playing and your suggestion helped me visualize it how to do it. Scheduled for next release.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Added a spinner so you can tell when OctoPod is trying to render the camera. I added a shorter timeout (used to be 60 seconds) so you can see the error and ask to retry again (https://github.com/gdombiak/OctoPod/issues/701)

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-18 at 17 35 38](https://github.com/user-attachments/assets/9893f7f6-97e7-4f49-b7f2-b67555308243)
