### ISSUE TITLE
Rename Label "HOTEND" to "EXTRUDER"

### ISSUE THREAD

**Issue by stahlfabrik** [gdombiak/OctoPod#7]
I just want to say: great to have a new alternative! An open source one even better!

I just had a quick look through the UI. I propose to change the label "HOTEND" to "EXTRUDER"  - as the HOTEND does not move the filament:-)

I have yet to try the app in action though. Also I have not seen the homing buttons. They are usually helpful as well

**Comment by gdombiak** [comment]
Thanks @stahlfabrik for this request. You can tell that I'm new to the world of 3D printing so still learning the jargon.
