### ISSUE TITLE
Feature request: Option to reload camera stream

### ISSUE THREAD

**Issue by dapetcu21** [gdombiak/OctoPod#701]
The webcam stream can get stuck for quite a lot of reasons:
* Poor connection
* App goes to sleep
* Encoding hitches on the raspberry pi

While ideally some these should be handled and recovered from by the app, a manual reload option would be great (I'm currently killing and restarting the app every time the webcam stream gets stuck)

I'm using OctoPi's new WebRTC webcam stack, if it's relevant.

**Comment by gdombiak** [comment]
This is a good idea. I realized that I swipe between cameras to force a refresh since I have multiple cameras which is not evident, optimal or available to everyone. Added to next release.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Feature implemented. Testing before pushing new release out. Probably some time this week.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-18 at 17 36 30](https://github.com/user-attachments/assets/6eb5b4ef-0e03-490e-b092-09bb95393384)

**Comment by gdombiak** [comment]
Hi @KayGundhardt,

The refresh button appears when any type of error happens while trying to render the camera. The user will have to manually press the button to retry if they want to give it another shot. Would this work for you?

Regards,
Gaston

**Comment by KayGundhardt** [comment]
Sure, that’s a progress :)But as I monitor my farms printers on some tablets running your app it would be great not running all the way from one to the next but them refreshing their viewport themselves when rendering errors occur… Could that maybe be integrated too?Am 19.08.2024 um 16:58 schrieb Gaston Dombiak ***@***.***>:﻿
Hi @KayGundhardt,
The refresh button appears when any type of error happens while trying to render the camera. The user will have to manually press the button to retry if they want to give it another shot. Would this work for you?
Regards,
Gaston

**Comment by gdombiak** [comment]
Hi @KayGundhardt, I implemented an exponential backoff algorithm so that OctoPod retries rendering the camera in case of a timeout with an increasing delay between retries. There is a maximum retry of 10 times and delay doubles between retries. That totals to 36 minutes of trying to render the camera before giving up. If the user manually clicks retry, reopens the app, switches camera or printer then retries reset to 0.
