### ISSUE TITLE
iPad Pro m4 camera feed is not working!

### ISSUE THREAD

**Issue by mc-ott** [gdombiak/OctoPod#708]
I have an iPad mini (5th gen) with ios 18.1.1 and an iPad Pro m4 with ios 18.1.1. The camera feed is not working on the iPad Pro m4 but it works on the iPad mini. I removed and reinstalled Octopod but it did not help, still no video feed, everything else looks ok.

**Comment by gdombiak** [comment]
Hi @mc-ott , could you share a screenshot of what you see on the iPad mini? I just tested it on the simulator and this is how the video appears on portrait and landscape modes.

![Simulator Screenshot - iPad mini (A17 Pro) - 2024-12-03 at 21 52 17](https://github.com/user-attachments/assets/ba998960-ac2a-4c1f-b517-3a25020d51b1)
![Simulator Screenshot - iPad mini (A17 Pro) - 2024-12-03 at 21 52 59](https://github.com/user-attachments/assets/3120acd3-bb5c-4657-b428-5416405b5b8e)


Thanks,
Gaston

**Comment by mc-ott** [comment]
iPad mini 5th gen works OK, I did not include the photos of the iPad mini. Only my iPad Pro M4 11”, Horizontal view video stream does not work, I just realized Portrait mode works sort of, smaller picture and bottom half of screen is empty. Maybe simulate with 11” screen size also if you already did not do it, photos below…Michel______     ______On Dec 4, 2024, at 12:53 AM, Gaston Dombiak ***@***.***> wrote:﻿
Hi @mc-ott , could you share a screenshot of what you see on the iPad mini? I just tested it on the simulator and this is how the video appears on portrait and landscape modes.
Simulator.Screenshot.-.iPad.mini.A17.Pro.-.2024-12-03.at.21.52.17.png (view on web)
Simulator.Screenshot.-.iPad.mini.A17.Pro.-.2024-12-03.at.21.52.59.png (view on web)
Thanks,
Gaston

**Comment by mc-ott** [comment]
iPad mini 5th gen works OK, I did not include the photos of the iPad mini. Only my iPad Pro M4 11”, Horizontal view video stream does not work, I just realized Portrait mode works sort of, smaller picture and bottom half of screen is empty. Maybe simulate with 11” screen size also if you already did not do it, photos below…
![IMG_0413](https://github.com/user-attachments/assets/8a161813-710f-4064-a5d2-8a7b4e2c53b0)
![IMG_0412](https://github.com/user-attachments/assets/74f0fd84-b577-4d66-b30f-f63641d7d8f5)

**Comment by gdombiak** [comment]
Hi @mc-ott , new release is out. Let me know how things work for you.

Thanks,
Gaston

**Comment by mc-ott** [comment]
Works well, identical . to my iPad mini.Thanks,Michel______     ______On Dec 6, 2024, at 1:00 AM, Gaston Dombiak ***@***.***> wrote:﻿
Hi @mc-ott , new release is out. Let me know how things work for you.
Thanks,
Gaston
