### ISSUE TITLE
Add support for push notifications

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#83]
This feature will let users receive notifications (with images if possible) when their print is done. We need to investigate with other events we can notify.

To implement this we will need to create an OctoPrint plugin.

**Comment by jollino** [comment]
I noticed an issue: the notifications are always quite a bit late. I also use the Telegram plugin to get real-time notifications every half-hour and upon specific events (start, pause, stop...) and the notifications from OctoPod are always late. Sometimes they're even clustered, e.g. those two that both came at 18:12 but referred to prior prints.
It doesn't affect me much as the Telegram messages are sent from OctoPrint directly, but I imagine that this may be a bit of an issue for those relying on OctoPod alone.

![img_3759](https://user-images.githubusercontent.com/3470104/48670953-696d0280-eb21-11e8-93b5-5e67db5e7024.jpg)
![img_3758](https://user-images.githubusercontent.com/3470104/48670956-6d992000-eb21-11e8-896d-5a022652d9d8.jpg)

Background app refresh for OctoPod is enabled; not sure what else may be causing this!

**Comment by Hedrakk** [comment]
For my part, I’m not getting any notification at all. I checked my notification settings and my background app refresh settings and everything seems to be fine. 

Is it because the functionality is still in development? 

Thanks
