### ISSUE TITLE
Domain Name with '-' Not accepted

### ISSUE THREAD

**Issue by hcanchristian** [gdombiak/OctoPod#92]
I tried to enter the hostname url which in my case contain a -. This is not accepted by the dialog.

**Comment by gdombiak** [comment]
Thanks for reporting this and good catch. Will include a fix for this in the next release. Waiting on 2 more translations and then new release will be out.

**Comment by hcanchristian** [comment]
Hi Gaston,

 

try http://octo-pi.int.my-domain.de

 

Regards

Christian

 

Von: Gaston Dombiak <notifications@github.com>
Antworten an: gdombiak/OctoPod <reply@reply.github.com>
Datum: Donnerstag, 4. Oktober 2018 um 05:30
An: gdombiak/OctoPod <OctoPod@noreply.github.com>
Cc: "christian@port-net.de" <christian@port-net.de>, Author <author@noreply.github.com>
Betreff: Re: [gdombiak/OctoPod] Domain Name with '-' Not accepted (#92)

 

I'm not being able to reproduce this. Can you give me an example of a URL that is not working with a -?

Tested things like: http://_23.we.com and works fine.

Thanks

**Comment by gdombiak** [comment]
Great. With that info I know what to fix now. :)

Testing local fix here and will soon push new version to the app store.
